
---
title: "Documentation for imfcharts"
date: "today"
author:
  - name: Datatools Team
    email: datatools-support@imf.org
    url: https://intlmonetaryfund.sharepoint.com/sites/fw-datatools
    department: 
      - name: ITD
      - url: http://datatools/
# bibliography: references.bib
number-sections: true
code-block-bg: "#F0F0F0"
format:
  html:
    # styles.css is needed to scale down figure sizes.
    # Specifying any of
    # #| out-width: "25%"
    # #| fig-width: 8
    # #| fig-height: 5
    # for individual figures does not have any effect.
    css: styles.css
    link-external-newwindow: true
    code-fold: true
    toc: true
    toc-depth: 2
    toc-float: true
    toc-location: left
    theme: custom-theme.scss # cyborg
    grid:
      body-width: 1200px  # Main body width
      margin-width: 150px # width of toc
      sidebar-width: 300px # left side
  docx:
    toc: true
    number-sections: true
    execute:
      echo: false

#  pdf:
#    documentclass: report
#    papersize: letter

# Adjust title font
include-in-header:
  - text: |
      <style>
        .title {
          font-size: 48px; /* Adjust the pixel value as needed */
          color: #4B82AD;    /* Optional: change the color */
        }
      </style>
jupyter: python3
---

<!-- 2025-11-20                                             -->
<!--                                                        -->
<!-- Documentation on imfcharts.                            -->
<!-- To generate this document run                          -->
<!-- quarto render imfcharts.qmd                            -->
<!--                                                        -->
<!-- Geneating PDF output will open a Carbon Black window   -->
<!-- but ignoring it will render the document.              -->

```{python}
#| label: py-imports
import os
import sys

# Create data dir
if not os.path.isdir('data'):
    os.makedirs('data')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

# Tables in quarto
from itables import show
from IPython.display import Markdown

import imf_datatools

from imfcharts import *
set_style('imf-articleiv')
```

<!------------------------------------------------------------------------------------------------------------------------------------>
# Introduction {#sec-intro}
This is the documentation for the `imfcharts` package.
The goal of this package is simple, to allow easy (re)production of IMF charts for publications.
The technology to do this has been available for decades, our goal is to make this as simple as it should be.
Furthermore, the technology we utilize is open source, meaning that the technology will be available for use
independent of any commercial entities. This will become increasingly important in the age of AI, as this provides
the Fund with a way of integrating with such systems but at the same time retaining the core technology in-house
so that we are not locked into one platform.

The authors wish to thank the [Process Modernization Challenge](https://imf.brightidea.com/Process){target="_blank"}
committee for their support and encouragement. The project started out as an [idea](https://imf.brightidea.com/D1580){target="_blank"}
for the Challenge, and in Feb 2025 the project [received First Place in the Challenge event](https://imf.brightidea.com/Process){target="_blank"}.

This document is orgnaized as follows.
In the next subsections @sec-quickstart is a Quick Start on how to install,
followed by  @sec-motivation Motivation, and examples are provided in @sec-gallery.
The following sections show the basics of chart creation in  @sec-basics, followed by how to switch styles in @sec-styles,
and integration with other systems are shown in @sec-R for R, @sec-stata for Stata and @sec-ai-excel for AI and Excel.

## Quick Start and Installation {#sec-quickstart}

The library is written in the Python language, but can be called from R (and perhaps in the future) Stata.
In all cases the Python library must be installed. This library is based on the well-known open source [Matplotlib](https://matplotlib.org/){target="_blank"}
library which is the basis for most Python visualization libraries.
Beyond Matplotlib the only dependencies are `numpy` and `pandas` so the library should be usable in any environment,
including those used within AI systems.

To install the library,

1. Install Python from the Software Center

2. Copy the folder `\\ecnswn12p\ems_shared\pub\datatools\dev\imfcharts` to your computer's `C:\ProgramData\Python3\Lib\site-packages` folder

3. Open Command Prompt and run the following:
    a. `ipython` Open ipython session
    b. `from imfcharts import *` If no error message appears the installation is complete
    c. `exit` Close session

Note that importing the library should create a copy of style files in your computer's `C:\User\[username]\.matplotlib\stylelib`
folder so they can be accessed by `Matplotlib`.

To create a chart, prepare a `pandas.DataFrame` with your data and set the index to be what the x-axis should be.
For example, in most cases a time series is plotted, so the index should be set to the dates.

A simple example is given below.

```{python}
#| label: quickstart
#| code-fold: show
#| fig-cap: "Simple GDP plot."

import pandas as pd
from imfcharts import *

# Create data
data = {'dates'                   : ['2024Q1', '2024Q2', '2024Q3', '2024Q4', '2025Q1'],
        'Consumption'             : [2.5, 3, 2.8, 2.7, 1.3],
        'Gov'                     : [1.2, 1.1, 0.8, 0.3, -0.2],
        'Net exports'             : [-0.5, 0.3, 1.2, 0.3, -1.5],
        'Fixed capital formation' : [0.2, 0.3, -0.2, -0.3, -0.3]}
df = pd.DataFrame(data).set_index('dates')
df['GDP'] = df.sum(axis=1)

# Get all columns except "GDP" for bars
barcols = list(df.columns)
barcols.remove('GDP')

# Create chart
chart = Chart(df, linecols='GDP', barcols=barcols)

# Show chart
chart
```

As can be seen, the code needed to generate the chart is the single line below:

```{python}
#| label: quickstart-chart
#| code-fold: show
#| eval: false
chart = Chart(df, linecols='GDP', barcols=barcols)
```

The chart automatically uses the default IMF Article IV colors, which is set by the library as the default colors.
Adding a few options will make the chart more presentable:

```{python}
#| label: quickstart-better
#| code-fold: show
#| fig-cap: "Modified GDP plot."

chart = Chart(df, linecols='GDP', barcols=barcols,
              attrs={'GDP' : {'color' : 'black'}},
              title='GDP by Composition', subtitle='(Seasonally Adjusted)',
              yrange=[-3, 5],
              legend_bottom=0.1, ncol_legend=2)
chart
```

The differences with the first chart are:

- Added title, subtitle
- Specified line for "GDP" to be black
- Specified y-axis range
- Moved legend bottom, specified number of columns in legend

All of these options and more are explained in @sec-basics.
The `chart` object can be saved with the command:

```{python}
#| label: quickstart-save
#| code-fold: show
#| eval: false

chart.save('GDP.pdf') # change extention to png etc.
```

and can be shown on screen with the command:

```{python}
#| label: quickstart-show
#| code-fold: show
#| eval: false

chart.show()
```

The `chart` variable is a `Chart` object within the library, and provides a direct interface with the underlying
`matplotlib.pyplot.Figure` (`chart.fig`) and `matplotlib.pyplot.Axes` (`chart.ax`) objects so that they can be modified further.
For example,  the popular [`seaborn`](https://seaborn.pydata.org/){target="_blank"} library is built on top of `Matplotlib`
so it can be called on the created `Chart`, and any Matplotlib function can be called on it.

<!-- TODO: Add example -->

## Motivation {#sec-motivation}

The Fund has wasted enormous resources and time by not provding a standard program to generate charts[^chart-programs],
and this has hurt the Fund in multiple ways:

1. People (especially young ones) are forced to repeat menial tasks ad nauseam
2. The mindset is stuck in Excel and people do not understand that technology can reduce these efforts significantly
3. The standards of visualization are stuck with outdated standards and terrible aesthetics

[^chart-programs]: The ITD CATS team provides the Excel PCF tool for this purpose, but this is still contained within Excel. Furthermore, it has not been updated for many years.

Therefore the goals of this project are:

1. Provide a package to easily generate existing IMF charts
2. Provide templates that allow users to easily switch to a new style

This allows Fund users to realize that menial tasks can be automated and done with much less effort.
Once a standard library is available and widely used, code written using it can then be reused.
It also incentivizes the Fund to move to better standards of visualization since the transition is now much easier and
does not require editing every single Excel chart that has been created previously.
The `imfcharts` library currently provides a "classic" IMF Article IV style (`imf-articleiv.mplstyle`)
but this can easily be expanded to other styles such as for WEO, GFSR, REO, etc., and in the future to any new styles.

While the main library is written in Python, it can also be called from R using a simple syntax transformation (in the future possibly from Stata),
which expands the user base.
Given recent advances in AI systems, it is also possible to use these tools through AI, so that even without any knowledge of programming,
users can use the library through generative AI tools.
The crucial point with AI is that although the AI system is the one calling the library, the library itself is maintained in-house and
the Fund retains full control of it. The use of open source, particularly Python ensures that any AI system can use it
while the Fund retains full control and rights to it.
See @sec-ai-excel on further details of usage with AI systems.

Another interesting future direction is integration with Excel so that the library can be called directly within Excel.
As Excel is not going to go away, there is a benefit to having the ability to easily generate charts in an almost native Excel way,
but still retaining the intellectual properties of the chart created and not relying on the Excel features to be provided indefinitely.

Finally, for users of Python and R, combining this library with the [datatools](http://datatools){target="_blank"} provides an end-to-end solution for
the analysis lifecycle:

1. data collection
2. data transformation
3. visualization/publication

all in very accessible and simple-to-use libraries. This is a  **fully reproducible and automated workstream**
which should greatly reduce the need to redo simple tasks over and over.

The library has also been designed so that charts can be exported and imported to a standard format like json which is indepdent of any program.
This would allow abstracting the features contained in the chart (such as colors, widths, etc.) and writing them to a file,
then later when the data has been updated, to generate the chart using those features.
For this purpose many of the functions like `lines()` are able to receive the inputs in a json format.
Full use of this feature would allow this library to be integrated into various data formats such as DMXe, CMFE, etc.

The goal of this library is to cover the 90% of instances where a chart is needed, and to be able to
provide a quick solution which is reproducible and usable by many people. Since it relies on the open source `Matplotlib` library,
further customizations of charts can be added as needed. The library is *not* intended as a package
to cover every single customized chart. The hope is that this library helps the evolution of the Fund in managing its data and assets
and it makes life easier for everyone who dares to try something new.

<span style="color:red;">TODO: EXPAND ON</span>

## Gallery {#sec-gallery}

Below are several examples along with the code used to generate them.

::: {.panel-tabset}

### Simple line chart

This is a simple line chart that is created with one command.
It uses the default IMF Article IV color scheme, so no line colors need to be specified.

```{python}
#| label: gallery_lines
#| fig-cap: "Simple line chart."
#| code-fold: show

# Get data from Haver (need imf_datatools)
col1, col2 = 'Unemployment rate', 'Combined rate of underemployment and unemployment (rhs)'
dict_series = {'S186ELUR@EMERGEMA' : col1,
	       'S186EUDR@EMERGEMA' : col2
               }
datafilename = 'data/unemp.csv'
if not os.path.isfile(datafilename):
    df = None
    for series in dict_series:
        _df = imf_datatools.get_haver_data(series)
        _df.columns = [dict_series[series]]
        # Merge
        if df is None:
            df = _df
        else:
            df = df.merge(_df, left_index=True, right_index=True, how='outer')
    df.to_csv(datafilename)
else:
    df = pd.read_csv(datafilename, index_col=0, parse_dates=[0])
# Create Chart object
chart = Chart(df, linecols=df.columns[0], rlinecols=df.columns[1],
               title='Labor Utilization', subtitle='(Percent)',
               xrange='2023-01:2025-08',
               yrange=[8, 11],
               )
chart
```

### Chart with line and bars

A chart that has a line and stacked bars.

```{python}
#| label: gallery_lines_bars
#| fig-cap: "A chart with a line and bars."
#| code-fold: show
infilename = 'data/turkey_page4/fig4_chart1_exp.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
linecol = 'Primary exp.'
barcols = list(df.columns)
barcols.remove(linecol)

# Create Chart object
attrs = {linecol             : {'linewidth' : 4, 'color' : IMFBLACK},
         'Personnel'         : {'color' : '#004C97', 'edgecolor' : 'red'},
         'Goods & services'  : {'color' : '#009CDE'},
         'Current transfers' : {'color' : '#CAEDFE'},
         'Capital exp.'      : {'color' : '#FF8200'},
         'Other' : {'color'  : '#DA291C'},                         
         }

chart1 = Chart(df, linecols=linecol, barcols=barcols,
               attrs=attrs,
               topaxis='left',
               title='Central Government: Primary Expenditure Components',
               subtitle='(Percent of GDP)',
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
chart1
```

### Area chart

An area chart along with a line.

```{python}
#| label: gallery_area
#| fig-cap: "A chart with a line and bars."
#| code-fold: show
infilename = 'data/turkey_page5/fig5_chart6_gross_international_reserves.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
gircol = 'Gross International Reserves (GIR)'
df.rename({gircol + ' (rhs)' :  gircol}, axis=1, inplace=True)

# Create Chart object
attrs = {gircol  : {'color' : '#416FA6'},
         'Gold'  : {'color' : '#CAEDFE'},
         'FX'    : {'color' : '#009CDE'}}

chart6 = Chart(df, linecols=gircol, areacols=['FX', 'Gold'],
               attrs=attrs,
               topaxis='right',
               title='Gross International Reserves',
               subtitle='(Billions USD)',
               xrange='2022-01:', yrange=[0, 200], ryrange=[-120, 40])
```

### Step chart

When drawing lines, set the option `drawstyle` to `steps-post` to set the line style to be steps.
This is useful for example when plotting the monetary policy rate.

```{python}
#| label: gallery_steps
#| fig-cap: "Line chart shown as steps."
#| code-fold: show
infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

attrs = {'Policy rate' : {'color' : IMFBLUE,
                          'drawstyle' : 'steps-post'},
         'Inflation'   : {'color' : IMFRED},
        }

# Create Chart object
chart3 = Chart(df, linecols=['Policy rate', 'Inflation'],
               attrs=attrs,
               title='steps',
               xrange='2023-01:', yrange=[0, 90])
```

### Chart with bars and right lines

A chart with bars on the left y-axis and a line on the right y-axis.

```{python}
#| label: gallery_lines_bars_right
#| fig-cap: "Chart with bars on left y-axis, lines on right y-axis."
# Get data
dict_series = {'N186FPAP@EMERGEMA' : 'Return to asset',
               'N186FNIE@EMERGEMA' : 'Return to equity'}
datafilename = 'data/banks.csv'
if not os.path.isfile(datafilename):
    df = None
    for series in dict_series:
        _df = imf_datatools.get_haver_data(series)
        _df.columns = [dict_series[series]]
        if df is None:
            df = _df
        else:
            df = df.merge(_df, left_index=True, right_index=True, how='outer')
    df.to_csv(datafilename)
else:
    df = pd.read_csv(datafilename, index_col=0, parse_dates=[0])
# Take 12-month rolling mean
df = df.rolling(12).mean()

attrs = {'Return to asset' : {'color' : IMFBLUE},
         'Return to equity' : {'color' : IMFRED}}

# Create Chart object
chart = Chart(df, barcols='Return to asset', rlinecols='Return to equity',
              topaxis='right',
              barlinewidth=0,
              attrs=attrs,
              title='Bank Profitability 1/',
              subtitle='(Percent, 12M moving average)',
              xrange='2022-01:', yrange=[0, 3], ryrange=[0, 30],
              legend_bottom=0.75, legend_left=0.55)

chart
```

### Scatter chart

```{python}
#| label: gallery_scatter
#| fig-cap: "A complicated plot with lines, bars and arrow, text."
#| code-fold: show
infilename = 'data/turkey_page2/fig2_chart4_inflation_forecast.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

attrs = {'Jul-23' : {'linewidth' : 0,
                     'color' : IMFBLACK,
                     # 'linestyle' : '--',
                     'marker' : 'o',
                     'markersize' : 10,
                     'markerfacecolor' : AXISGRAY,
                     'markeredgewidth' : 0,
                     'markeredgecolor' : AXISGRAY},
         'Nov-23' : {'linewidth' : 4,
                     'color' : IMFRED,
                     # 'linestyle' : '--',
                     'marker' : 'o',
                     'markersize' : 10,
                     'markerfacecolor' : IMFRED,
                     'markeredgewidth' : 0,
                     'markeredgecolor' : IMFRED},
         'Feb-24' : {'linewidth' : 0,
                     'color' : '#89A54E',
                     # 'linestyle' : '--',
                     'marker' : '^',
                     'markersize' : 10,
                     'markerfacecolor' : '#89A54E',
                     'markeredgewidth' : 0,
                     'markeredgecolor' : '#89A54E'},
         'May-24' : {'linewidth' : 0,
                     'color' : '#6E548D',
                     # 'linestyle' : '--',
                     'marker' : 'x',
                     'markersize' : 10,
                     'markerfacecolor' : '#6E548D',
                     'markeredgewidth' : 2,
                     'markeredgecolor' : '#6E548D'},
         'Aug-24' : {'linewidth' : 0,
                     'color' : '#3D96AE',
                     # 'linestyle' : '--',
                     'marker' : 'x|',
                     'markersize' : 10,
                     'markerfacecolor' : '#3D96AE',
                     'markeredgewidth' : 2,
                     'markeredgecolor' : '#3D96AE'},
         'Nov-24' : {'linewidth' : 4,
                     'color' : '#FFC000',
                     # 'linestyle' : '--',
                     'marker' : 'o',
                     'markersize' : 10,
                     'markerfacecolor' : '#FFC000',
                     'markeredgewidth' : 0,
                     'markeredgecolor' : '#FFC000'},
         'Feb-25' : {'linewidth' : 0,
                     'color' : IMFBLACK,
                     # 'linestyle' : '--',
                     'marker' : '+',
                     'markersize' : 10,
                     'markerfacecolor' : IMFBLACK,
                     'markeredgewidth' : 2,
                     'markeredgecolor' : IMFBLACK},
         'May-25' : {'linewidth' : 0,
                     'color' : '#FFC000',
                     # 'linestyle' : '--',
                     'marker' : '_',
                     'markersize' : 10,
                     'markerfacecolor' : '#C55A11',
                     'markeredgewidth' : 1,
                     'markeredgecolor' : '#C55A11'},
         'Aug-25' : {'linewidth' : 4,
                     'color' : '#7030A0',
                     # 'linestyle' : '--',
                     'marker' : 's',
                     'markersize' : 10,
                     'markerfacecolor' : '#7030A0',
                     'markeredgewidth' : 0,
                     'markeredgecolor' : '#7030A0'},
}

# Create Chart object
chart4 = Chart(df, linecols=df.columns,
               attrs=attrs,
               title="CBRT's Inflation Forecast",
               subtitle='(Percent, end-year inflation)',
               ncol_legend=2, legend_left=0.45, legend_width=0.40,
               yrange=[0, 70])
chart4
```

### Categorical bar chart

```{python}
#| label: gallery_categorical_bars
#| fig-cap: "A complicated plot with lines, bars and arrow, text."
#| code-fold: show
# Read in data
infilename = 'data/turkey_page5/fig5_chart3_terms_of_trade.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0)
attrs = {'shock' : {'color' : '#BFBFBF',
                    'barcolors' : [{'TUR' : 'red'},
                                  ]
                   }
        }
# Create Chart object
chart3 = Chart(df, barcols=df.columns, barstack=False, # baraxis='right',
               attrs=attrs,
               barlinewidth=0, xtickangle=90, xticklength=0,
               title='Terms of Trade Shock, 2025Q2 or Latest',
               subtitle='(Percent change from 2023 average)',
               yrange=[-15, 15],
               legend=False)
chart3
```

### Chart with lines, shading, fill

```{python}
#| label: gallery_extras
#| fig-cap: "A chart with lines, shading, and filling."
#| code-fold: show
# Read in data
infilename = 'data/turkey_page1/fig1_chart1_gdp.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
gdpcol = cols[0]

# Add "forecast" around gdpcol
df['25'] = df[gdpcol] - 1.0 * np.random.rand(len(df))
df['75'] = df[gdpcol] + 1.0 * np.random.rand(len(df))
df['5']  = df['25'] - 4.  * np.random.rand(len(df))
df['95'] = df['75'] + 4.  * np.random.rand(len(df))

df.loc[:'2022Q1', ['5', '25', '75', '95']] = np.nan

attrs = {gdpcol : {'linewidth' : 2,
                   'color' : '#004C97',
                   'marker' : 'o',
                   'markersize' : 4}
         }
kw_hline = {'y' : 1.4, 'xrange' : '2023Q1:' + df.index[-1].strftime('%Y-%m'),
            'color' : IMFBLACK, 'linewidth' : 1.5, 'linestyle' : '--', 'dashes' : [10, 4]}

kw_vline = {'x' : '2020-03',
            'color' : IMFRED, 'linewidth' : 1.5, 'linestyle' : '--'}

kw_fills  = [{'lo' : '25',   'hi' : gdpcol, 'color' : '#CAEDFE'},
             {'lo' : gdpcol, 'hi' : '75',   'color' : '#CAEDFE'},
             {'lo' : '5',   'hi' : '25',    'color' : '#004C97'},
             {'lo' : '75', 'hi' : '95',     'color' : '#004C97'},
            ]

kw_vrect = {'xmin' : '2021Q1', 'xmax' : '2022Q1', 'color' : 'grey', 'alpha' : 0.3}

chart1 = Chart(df, linecols=gdpcol,
               attrs=attrs,
               title='Real GDP Growth and Forecast',
               subtitle='(Percent, q/q)',
               xrange='2020Q1:', yrange=[-12, 18],
               hlines=[kw_hline],
               vlines=[kw_vline],
               vrects=[kw_vrect],
               fills=kw_fills,
               )
chart1
```

### Chart with lines, bars, arrows, text

```{python}
#| label: gallery_gdp
#| fig-cap: "A complicated plot with lines, bars and arrow, text."
#| code-fold: show
# This file has a lot of transformations so copy the data file into the repository.
# To re-generate run examples/get_data_turkey_page1.py and examples/examples_turkey_page1.py.
infilename = 'data/turkey_page1/fig1_chart1_gdp.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist, run example files for Turkey page 1')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
linecol = cols[0]
barcols = cols[1:]

# Create Chart object

attrs = {linecol : {'linewidth' : 4,
                    'color' : '#004C97',
                    # 'linestyle' : '--',
                    'marker' : 'o',
                    'markersize' : 10,
                    'markerfacecolor' : 'white',
                    'markeredgewidth' : 4,
                    'markeredgecolor' : '#004C97'},
         'Consumption (private)' : {'color' : '#4B8CAD', 'hatchcolor' : IMFBLUE, 'hatch' : '\\\\'},
         'Consumption (public)' : {'color' : 'white', 'hatch' : '\\\\\\', 'hatchcolor' : IMFBLACK},
         'Net exports' : {'color' : IMFGREY},
         'Inventories/discrepancy' : {'color' : IMFRED},
         'Fixed investment' : {'color' : 'white',
                               'hatch' : '///',
                               'hatchcolor' : IMFGREEN,
                               'hatchwidth' : 10}
         }

chart1 = Chart(df, linecols=linecol, barcols=barcols,
               attrs=attrs,
               title='Contributions to Real GDP Growth',
               subtitle='(Percent, q/q)',
               xrange='2023Q1:', yrange=[-5, 9.5], ryrange=[-5, 9.5],
               ncol_legend=2)

# Add hline
chart1.hline(y=1.4, xrange='2023Q1:' + df.index[-1].strftime('%Y-%m'),
             # xrange=[0.05, 0.95], coordinates='axis',
             color=IMFBLACK, linewidth=2.5, linestyle='--', dashes=[10, 4])

# Add text
text = '''Real GDP growth\nlong-run average\n(1.4 q/q)'''
chart1.text(pd.Timestamp('2024Q3'), 6.5, text=text, fontweight='bold', color='#004C97')

# Add arrow
chart1.arrow(head=[pd.Timestamp('2025Q1'), 1.5],
             tail=[pd.Timestamp('2025Q1'), 5],
             color='#004C97')
chart1
```

:::

## About this Document

This document was generated by [Quarto](https://quarto.org/){target="_blank"}, a document generation program.
To generate this document yourself, open Command Prompt and do the following.
It is assumed you have R and RStudio installed from the Software Center, which installs Quarto.

```bash
cd C:\ProgramData\Python3\Lib\site-packages\imfcharts\doc
# If necessary specify full path to quarto
# C:\Program Files\RStudio\resources\app\bin\quarto\bin\quarto.exe render imfcharts.qmd
quarto render imfcharts.qmd
```

and this will generate the HTML and Word output files.

All of the code used to generate the output charts are embedded in the HTML version
of this document, and can be pasted and used directly (as long as the corresponding data is also copied appropriately).
To download the data, the `imf_datatools` library is needed, see [the website](http://datatools) for instructions.

<!------------------------------------------------------------------------------------------------------------------------------------>
# Basic Usage {#sec-basics}

Below basic usage of the `imfcharts` package is shown.
For most purposes it should be possible to create a `Chart` object with a single call to the `Chart()` function
by specifying the data to be charted (a `pandas.DataFrame`) and the columns to be shown as lines, bars, area, fills, along with
arguments to specify the title, axis ranges, etc.
It is possible to modify a generated chart by calling additional functions on it such as

```{python}
#| label: basics-first
#| code-fold: show
#| eval: false

# Add bars
chart.bars(data=df, cols='Inflation')

# Set x-axis range
chart.xrange([0, 3])

# Set title
chart.title('Domestic Growth (Annual)')

# Add horizontal band
chart.hrect(y0=0, y1=3, color='grey', alpha=0.3)
```

In all functions there is a natural and default order of how style features are determined.
The initial settings are determined by the style being used, which will default to `imf-articleiv.mplstyle` and
can also be set manually with

```python
from imfcharts import *
set_style('imf-articleiv')
```

This is a [`Matplotlib` style sheet](https://matplotlib.org/stable/users/explain/customizing.html){target="_blank"}
which specifies chart defaults like title fonts, default colors, tick lengths, etc.
When no options are specified, options specified in this style sheet will be used, so switching to
another style sheet like that for WEO would change to the default WEO color scheme.

The second level, if available is by specifying a characteristic for a specific chart, typically at creation.
For example, to keep all of the Article IV style except the default colors used, create a `Chart` with
```python
chart = Chart(colors=['red', 'green', 'blue'], linewidth=3)
````
and this will generate a chart that cycles through the specified red, green, blue colors for each object plotted,
and set all line charts to have a linewidth of 3 instead of the default `axes.linewidth: 1` specified in the Article IV style file.

The third level is to specify each characteristic at the individual level, typically using the `attrs` argument:
```python
chart = Chart(df, linecols='GDP',, rlinecols='Unemployment',
              linewidth=3,
              attrs={'GDP'          : {'color' : 'black'}},
                     'Unemployment' : {'color' : 'red', 'linewidth' : 1}}
                    }
```

When specified, the `attrs` override the style settings and any class-level settings if specified.
For example in the above, the style file specifies a linewidth of 1, but this is overridden by
the class-level settings of `linewidth=3`, and this is further overridden by the `attrs` argument
for each line. The line for `'GDP'` will therefore have a linewidth of 2, and `'Unemployment'` will have a linewidth of 1.

While the `Chart()` creation function conveniently provides a way to specify almost all possible input parameters
so that a chart can be created with one call, internally it will call functions like `lines()` and `bars()` which
ensures that the output is consistent between specifying the lines and bars at creation time or adding them later.

It should also be noted that when creating a `Chart` object and adding lines, bars, and area,
the order in which these are drawn is

1. area
2. bars
3. lines

since this is the natural way these would be shown (i.e., area graphs would be in the background,
bars would be shown on top, and lines are shown on top of both so they are not obstructed).
The `colors` argument specifies the colors to cycle through as each component is drawn,
and is shared by lines, bars and area graphs. So for example in the following:
```python
chart = Chart(df, linecols='line',
              barcols=['bar1', 'bar2'],
              area=['area1', 'area2'])
```
the first two colors of the color cycle will be used for the area graph columns `'area1'` and `'area2'`,
and the third and fourth colors will be used for the bar columns `'bar1'` and `'bar2'`,
and lastly the fifth color will be used for the line column `'line'`.
Since it is a color cycle, if the number of colors specified is less than the total number of columns
the colors will be recycled. In general the `colors` argument which can be provided when creating
the `Chart` object should have at least as many colors as the number of columns to be shown, otherwise colors will be reused.
The order of plotting for a variable like `linecols` will be as it is specified, regardless of any order
within the original `pandas.DataFrame` column order.

The below subsections first explain the basics of creating lines, bars and area charts.
In each of these cases they can be specified directly when creating the `Chart` object,
or can be called later with functions like `chart.lines()`. Next, adding annotations such as
horizontal/vertical lines and rectangles are shown in @sec-basics-lines_rects, followed by
adjusting titles, legends, and showing, saving the chart in @sec-basics-additional.

## Line Charts {#sec-basics-lines}

The most straightforward use case is to create a line chart, typically a time series chart.
The `Chart()` function will take in a `pandas.DataFrame` and argument `linecols` which can either be a
`str` specifying a column name or an iterable of column names.

```{python}
#| label: lines
#| fig-cap: "A plot with lines"
#| code-fold: show
# Read in data
infilename = 'data/turkey_page1/fig1_chart2_labor.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
unemp = df.columns[0]
combined = df.columns[1]

# Create Chart object
chart2 = Chart(df, linecols=unemp, rlinecols=combined,
               title='Labor Utilization', subtitle='(Percent)',
               xrange='2023-01:2025-08', yrange=[8, 11])
chart2
```

Note that in the above example, the argument `linecols` and `rlinecols` are used
to specify the columns to be plotted on the left and right y-axes, respectively,
and they are plotted with different scales.
Furthermore, the colors have defaulted to the IMF Article IV style, showing as the usual red and blue colors.

To further customize the lines, the `attrs` option can be used which is a `dict` between each
column to be plotted and its attributes. For example, to change the line colors from the defaults:

```{python}
#| label: lines_color
#| fig-cap: "Specify line colors."
#| code-fold: show

# Create Chart object
chart2 = Chart(df, linecols=unemp, rlinecols=combined,
               attrs={unemp : {'color' : 'black'},
                      combined : {'color' : 'orange'}},
               title='Labor Utilization', subtitle='(Percent)',
               xrange='2023-01:2025-08', yrange=[8, 11])
chart2
```

In the above the variable `attrs` is a `dict` with keys corresponding to the line columns.
The colors of each line are specified with the key `color` and corresponding color.
For a list of valid numbers see @sec-basics-misc-colors.

The available keys for a column within `attrs` for `lines()` are:

| Variable | Description |
|---|---|
| color | Line color, specify as valid color given in @sec-basics-misc-colors |
| linewidth | Line width of marker |
| dashes | Line style, default is `'-'` for solid lines, specify a [valid line style](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"} |
| linestyle | A valid `Matplotlib` line style specified [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"}. Special implementations such as "imfdash", "imfround" are implemented which mimic Excel styles. |
| marker | Specify the marker (default no marker) using one of symbols [here](https://matplotlib.org/stable/api/markers_api.html){target="_blank"}. Specifying multiple symbols together like "x\|" will combine the symbols in the legend. |
| markersize | Size of marker |
| markerfacecolor | Face color of marker |
| markeredgecolor | Edge color of marker |
| markeredgewidth | Edge width of marker |
| drawstyles | Can be used to draw step-like lines which are used for example for policy rates, options are 'default', 'steps', 'steps-pre', 'steps-mid', 'steps-post'; typically for a policy rate chart the option 'steps-pre' would be used. |
| dashes, dash_capstyle | Advanced options to specify cap styles |
| legend | If `False`, do not show this entry in the legend |

: {tbl-colwidths="[10,90]"}

A fuller example is below.
```{python}
#| label: lines_all_options
#| fig-cap: "Full example of line options."
#| code-fold: show

# Specify all attributes in detail
attrs = {unemp : {'color' : (0.22, 0.5, 0.9, 0.7),
                  'linestyle' : 'dashed',
                  'linewidth' : 3,
                  'marker' : 'x|', # combine markers
                  'markeredgecolor' : 'purple',
                  'markersize' : 12,
                  'markeredgewidth' : 2,
                 },
         combined : {'color' : 'salmon',
                     'linestyle' : 'dotted',
                     'legend' : False, # don't show in legend
                     'marker' : 'o',
                     'markersize' : 12,
                     'markerfacecolor' : '#00CCCC',
                     'markeredgecolor' : '#AB2323',
                     'markeredgewidth' : 3,
	            }
	}

# Create Chart object
chart2 = Chart(df, linecols=unemp, rlinecols=combined,
               attrs=attrs,
               title='Labor Utilization', subtitle='(Percent)',
               xrange='2023-01:2025-08', yrange=[8, 11])
chart2
```

Internally, lines are added with the function `Chart.lines()`, options for this function are the following.

| Argument | Default | Description |
|---|---|---|
| data | None | Data to use, in the form of a `pandas.DataFrame`. If no data is specified, will try to use any data that was previously specified to create this chart |
| cols | None | The columns in the data to be charted as lines. Note that when calling `Chart()`, this option is `barcols`. An iterable of column names, or if a single column can use a `str`.|
| indexcol | None | By default the input `pandas.DataFrame`'s index is used as the x-axis. If this is a column in the DataFrame, specify using this option. |
| axis | 'left' | Specify which y-axis to plot on, choose either 'left' or 'right' |
| colors | None | Specify an iterable of valid colors to be used as the color cycle, if not specified will default to what is specified in the current style |
| linewidth | None | If specified, override what is specified in the current style and apply as default to all lines drawn in this call |
| linebreaks | False | If `linebreaks=False`, then connect the lines even if there are NA values. |
| drawstyle | None | Set all lines to use the specified drawstyle for example to create step charts, see example [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/step_demo.html){target="_blank"} |
| attrs | None | Attributes for individual columns. |
| xrange | None | Specify x-axis range. See @sec-basics-format_axes. |
| margins | None | If specified, set how additional margins are added. Default is 'auto' which will automatically adjust. Can also specify number of days as integers. |
| xformat | None | Specify how x-axis is formatted for a time series plot. Default is to check the frequency of the data and automatically determine. Otherwise specify a frequency like 'D', 'W', 'M', 'Q', 'A' for daily, weekly, monthly, quarterly or annual frequency. |
| yrange | None | Override existing `yrange` of this object and set y-axis range |
| ryrange | None | Override existing `ryrange` of this object and set right y-axis range |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

When drawing lines, set the option `drawstyle` to `steps-post` to set the line style to be steps.
This is useful for example when plotting the monetary policy rate.

Below is a gallery of various line charts and options.

::: {.panel-tabset}

### No options (Article IV style)

```{python}
#| label: gallery_lines_nooptions
#| fig-cap: "Line chart (no options)."
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

chart = Chart(df, linecols=df.columns,
              title='No Options')
```

### Class-level options

```{python}
#| label: gallery_lines_classoptions
#| fig-cap: "Line chart with class-level options."
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

chart = Chart(df, linecols=df.columns,
              title='Class-level Options',
              colors=['red', 'green', 'blue'],
              linewidth=3,
              xrange='2023-01:', yrange=[0, 90])
```

### Attributes

```{python}
#| label: gallery_lines_attrs
#| fig-cap: "Line chart with individual attributes specified."
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
attrs = {'Policy rate' : {'color' : IMFBLUE, 'linewidth' : 2},
         'Inflation' : {'color' : IMFRED, 'marker' : 'o', 'markersize' : 3, 'markerfacecolor' : 'red', 'markeredgecolor' : 'black'},
         'Inflation expectation' : {'color' : IMFBLACK, 'linestyle' : '--'}}

chart = Chart(df, linecols=df.columns,
              title='Attributes',
              attrs=attrs,
              xrange='2023-01:', yrange=[0, 90])
```

### Add to existing `Chart` with `lines()`

```{python}
#| label: gallery_lines_calllines
#| fig-cap: "Add lines to existing chart."
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
chart = Chart(title='Class-level Options')

# Call lines on existing chart
attrs = {'Policy rate' : {'color' : IMFBLUE, 'linewidth' : 2},
         'Inflation' : {'color' : IMFRED, 'marker' : 'o', 'markersize' : 3, 'markerfacecolor' : 'red', 'markeredgecolor' : 'black'},
         'Inflation expectation' : {'color' : IMFBLACK, 'linestyle' : '--'}}
chart.lines(data=df, cols=df.columns,
            attrs=attrs,
            xrange='2023-01:', yrange=[0, 90])
```

### Step chart

When drawing lines, set the option `drawstyle` to `steps-post` to set the line style to be steps.
This is useful for example when plotting the monetary policy rate.

```{python}
#| label: gallery_lines_steps
#| fig-cap: "Line chart shown as steps."
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

attrs = {'Policy rate' : {'color' : IMFBLUE,
                          'drawstyle' : 'steps-post'},
         'Inflation'   : {'color' : IMFRED},
        }

# Create Chart object
chart = Chart(df, linecols=['Policy rate', 'Inflation'],
              attrs=attrs,
              title='steps',
              xrange='2023-01:', yrange=[0, 90])
```

### Use `dict` as Input to `lines()`

```{python}
#| label: gallery_lines_kwargs
#| fig-cap: "Add lines to existing chart using `dict`."
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
chart = Chart(title='Class-level Options')

# Call lines on existing chart
attrs = {'Policy rate' : {'color' : IMFBLUE, 'linewidth' : 2},
         'Inflation' : {'color' : IMFRED, 'marker' : 'o', 'markersize' : 3, 'markerfacecolor' : 'red', 'markeredgecolor' : 'black'},
         'Inflation expectation' : {'color' : IMFBLACK, 'linestyle' : '--'}}
kwargs = {'data' : df, 'cols' : df.columns,
          'attrs' : attrs,
          'xrange' : '2023-01:', 'yrange' : [0, 90]}
chart.lines(**kwargs)
```

:::


## Add Bars {#sec-basics-bars}

To add bars, use the argument `barcols` in `Chart()` or use the function `Chart.bars()` on an existing `Chart` with the argument `cols`.
The argument can either be a `str` specifying a single column or an iterable of multiple column names,
and the default is to have all bars stacked.

An example is shown below.

```{python}
#| label: basics_barchart
#| fig-cap: "Generate bar chart data."
datafilename = 'data/gdp.csv'
df = pd.read_csv(datafilename, index_col=0, parse_dates=[0])
df['Consumption (private)'] = df['Consumption1'] + df['Consumption2']
df['Net exports'] = df['Exports'] - df['Imports']
df['Inventories/discrepancy'] = df['Real GDP growth'] - df['Consumption (private)'] - df['Consumption (public)'] - df['Fixed investment'] - df['Net exports']

gdpcol = 'Real GDP growth'
barcols = ['Consumption (private)', 'Consumption (public)', 'Net exports', 'Inventories/discrepancy', 'Fixed investment']
df = df[[gdpcol] + barcols].copy()
# Normalize change by previous GDP value
for barcol in barcols:
    df[barcol] = 100. * df[barcol].diff() / df[gdpcol].shift()
# Calculate %pop for GDP
df[gdpcol] = imf_datatools.dataframe_utilities.calc_pop(df[gdpcol])
```

```{python}
#| label: barchart
#| fig-cap: "Example bar chart."
#| code-fold: show
linecol = cols[0]
barcols = cols[1:]

# Create Chart object
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='Contributions to Real GDP Growth',
               subtitle='(Percent, q/q)',
               xrange='2023Q1:', yrange=[-5, 9.5], ryrange=[-5, 9.5],
               ncol_legend=2)
chart1
```

Similar to plotting lines, an option `attrs` can be passed in to specify the attributes of each bar.
The default is to follow the color scheme that is specified in the current style, and we see the bars
having the familiar Article IV colors.


The available options in `attrs` for bars is as follows:

| Variable | Description |
|---|---|
| color | The color of bars for this column. |
| width | Specify width of bars. If time series, in units of days. |
| offset | Additional offset for bars. If time series, in units of days. |
| edgecolor | Edge colors of bars. |
| hatchcolor | Specify colors for any hatches |
| hatch | Specify a valid hatch specified [here](https://matplotlib.org/stable/gallery/shapes_and_collections/hatch_style_reference.html){target="_blank"} |
| hatchwidth | Specify hatch bar width |
| edgecolor | Specify color of lines for the edges of the bars. |
| legend | If `False`, do not add to legend. |
| barcolors | Specify color of individual colors of bars using the index of the data. See example below. |
| offset | If `stack=False`, specify custom offset of x-axis position for this column. |

: {tbl-colwidths="[10,90]"}

The `attrs` keywords are set so that when possible, for example for `color` it is the same as with those for when calling `lines()`,
so that it is easy to switch from a line chart to a bar chart using the same `attrs` if the attributes are the same.

Also note that the default is to have the edges of bars in black. This color can be modfiied with `baredgecolor` for each column,
and to remove use the option `barlinewidth=0` when calling `Chart()` or `Chart.bars()`.

An example with customized bar `attrs` is below.

```{python}
#| label: barchart_options
#| fig-cap: "Example bar chart."

# Create Chart object
attrs = {linecol : {'linewidth' : 4,
                    'color' : '#004C97',
                    # 'linestyle' : '--',
                    'marker' : 'o',
                    'markersize' : 10,
                    'markerfacecolor' : 'white',
                    'markeredgewidth' : 4,
                    'markeredgecolor' : '#004C97'},
         'Consumption (private)'   : {'color' : '#4B8CAD', 'barhatchcolor' : IMFBLUE, 'barhatch' : '\\\\'},
         'Consumption (public)'    : {'color' : 'white', 'barhatch' : '\\\\\\', 'barhatchcolor' : IMFBLACK},
         'Net exports'             : {'color' : IMFGREY},
         'Inventories/discrepancy' : {'color' : IMFRED},
         'Fixed investment'        : {'color' : 'white', 'barhatch' : '///','barhatchcolor' : IMFGREEN, 'barhatchwidth' : 10}
         }

chart1 = Chart(df, linecols=linecol, barcols=barcols,
               attrs=attrs,
               topaxis='left',
               title='Contributions to Real GDP Growth',
               subtitle='(Percent, q/q)',
               xrange='2023Q1:', yrange=[-5, 9.5], ryrange=[-5, 9.5],
               ncol_legend=2)
chart1
```

Internally, bar charts are created with the function `chart.bars()`.
As with `lines()`, the attributes of each bar are determined in the order of

1. Style options
2. Class-level options specified either when calling `Chart()` or `Chart.bars()`
3. Individual column level using `attrs`.

Options for `Chart.bars()` are:

| Argument | Default | Description |
|---|---|---|
| data | None | Data to use, in the form of a `pandas.DataFrame`. If no data is specified, will try to use any data that was previously specified to create this chart |
| cols | None | The columns in the data to be charted as lines. Note that when calling `Chart()`, this option is `linecols` and `rlinecols` to distinguish from columns for bars and area graphs. An iterable of column names, or if a single column can use a `str`.|
| indexcol | None | By default the input `pandas.DataFrame`'s index is used as the x-axis. If this is a column in the DataFrame, specify using this option. |
| axis | None | Specify which y-axis to plot on. Note that when calling `Chart()` this is specified as `baraxis` |
| stack | True | Specify whether to stack bars. If `True`, all bars are stacked on top of each other (default), otherwise they are staggered. when calling `Chart()` this is specified as `barstack`. |
| total_barwidth |None | When not plotting bars as a time series, specify the width of each bar, default is 0.9. |
| linewidth |None | Width of edges of bars. When calling `Chart()` this is specified as `barlinewidth`. |
| edgecolor | None | Edge color for bars. If not specified defaults to style default (black for Article IV). When calling `Chart()` this is specified as `baredgecolor`. |
| attrs | None | Attributes for individual columns. |
| xrange | None | Specify x-axis range. See @sec-basics-format_axes. |
| margins | None | If specified, set how additional margins are added. Default is 'auto' which will automatically adjust. Can also specify number of days as integers. |
| xformat | None | Specify how x-axis is formatted for a time series plot. Default is to check the frequency of the data and automatically determine. Otherwise specify a frequency like 'D', 'W', 'M', 'Q', 'A' for daily, weekly, monthly, quarterly or annual frequency. |
| yrange | None | Override existing `yrange` of this object and set y-axis range |
| ryrange | None | Override existing `ryrange` of this object and set right y-axis range |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

Again, note that many options are the same as for `Chart.lines()`.
Below is a gallery of bar charts with various options.

::: {.panel-tabset}

### No options (Article IV style)

```{python}
#| label: gallery_bars_nooptions
#| fig-cap: "Bar chart (no options)."
#| code-fold: show
infilename = 'data/turkey_page4/fig4_chart1_exp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
linecol = 'Primary exp.'
barcols = list(df.columns)
barcols.remove(linecol)
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='no options',
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Color Cycle

```{python}
#| label: gallery_bars_colors
#| fig-cap: "Color cycle."
#| code-fold: show
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='color cycle',
               colors=['red', 'green', 'blue', 'black'],
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Axis Right

```{python}
#| label: gallery_bars_axis_right
#| fig-cap: "Axis right."
#| code-fold: show
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='axis right',
               baraxis='right',
               xrange='2018-01:', ryrange=[0, 30],
               ncol_legend=2)
```

### Bar Edge Color/Width

In the below `baredgecolor` is set to `'gold'` and the edge line width is given with `barlinewidth=3`.

```{python}
#| label: gallery_bars_edges
#| fig-cap: ":Edge color and width."
#| code-fold: show
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='bar edges',
               baredgecolor='gold',
               barlinewidth=3,
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Margins

In the below `margins` is set to 170 days.
Since for annual frequency data the bar is set by default to 335 days,
this removes most of the side margin for the chart.

```{python}
#| label: gallery_bars_margins
#| fig-cap: "Specify margins."
#| code-fold: show
# Create Chart object
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='margins',
               margins=120,
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Attributes

In the below a `dict` called `attrs` is passed in to specify the colors of each bar.

```{python}
#| label: gallery_bars_attrs
#| fig-cap: "Specify attributes."
#| code-fold: show
attrs = {linecol : {'linewidth' : 4, 'color' : IMFBLACK},
         'Personnel' : {'color' : '#004C97'},
         'Goods & services' : {'color' : '#009CDE'},
         'Current transfers' : {'color' : '#CAEDFE'},
         'Capital exp.' : {'color' : '#FF8200'},
         'Other' : {'color' : '#DA291C'},                         
         }

# Create Chart object
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               title='attrs',
               attrs=attrs,
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Add Bars From a `dict`

In the below the function `bars()` is called with a `dict` which is passed in as `**kwargs**`.

```{python}
#| label: gallery_bars_kwargs
#| fig-cap: "Create from `dict`."
#| code-fold: show
chart1 = Chart(title='kwargs',
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)

# Add line using dict
kwargs_lines = {'data' : df,
                'cols' : linecol,
                'attrs' : attrs}
chart1.lines(**kwargs_lines)

# Add bars using dict
kwargs = {'data' : df,
          'cols' : barcols,
          'attrs' : attrs,
          }
chart1.bars(**kwargs)
```

### Unstacked

In the below the option `stack=False` is passed in.

```{python}
#| label: gallery_bars_unstacked
#| fig-cap: "Unstacked."
#| code-fold: show
chart1 = Chart(df, linecols=linecol, barcols=barcols,
               barstack=False,
               attrs=attrs,
               title='stack=False',
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Specify individual colors

To specify colors for individaul bars, set them in `attrs` by
specifying for that column the key `"barcolor"` and passing in a `list` of `dicts` between
the index and the color.

In the below example, the column "Personnel" will get a red color for the periods 2022 and 2024.

```{python}
#| label: gallery_bars_individual_colors
#| fig-cap: "Individual colors."
#| code-fold: show

attrs = {linecol : {'linewidth' : 4, 'color' : IMFBLACK},
         'Personnel' : {'color' : '#004C97', 'baredgecolor' : 'red',
                        'barcolors' : [{'2022' : 'red'}, {'2024' : 'red'}]},
         'Goods & services' : {'color' : '#009CDE'},
         'Current transfers' : {'color' : '#CAEDFE'},
         'Capital exp.' : {'color' : '#FF8200'},
         'Other' : {'color' : '#DA291C'},                         
         }

chart1 = Chart(df, linecols=linecol, barcols=barcols,
               attrs=attrs,
               title='individual colors',
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
```

### Categorical, unstacked

In the below a `pandas.DataFrame` with a categorical index is shown as a bar chart that has `stack=False`.

```{python}
#| label: gallery_bars_categorical
#| fig-cap: "Categorical."
#| code-fold: show
infilename = 'data/turkey_page5/fig5_chart3_terms_of_trade.csv'
df = pd.read_csv(infilename, index_col=0)

chart3 = Chart(df, barcols=df.columns, barstack=False,
               xtickangle=90, xticklength=0,
               title='categorical, no stack',
               yrange=[-15, 15])
```

### Categorical, unstacked individual colors

In the below, the bar color for "TUR" is set to red.

```{python}
#| label: gallery_bars_categorical_colors
#| fig-cap: "Categorical with individual colors"
#| code-fold: show
attrs = {'shock' : {'color' : '#BFBFBF',
                    'barcolors' : [{'TUR' : 'red'}]}
        }
chart3 = Chart(df, barcols=df.columns, barstack=False,
               attrs=attrs,
               xtickangle=90, xticklength=0,
               title='categorical, no stack with colors',
               yrange=[-15, 15],
               legend=False)
```

:::

## Add Area {#sec-basics-area}

An area graph is very similar to a bar graph, and can be drawn with either the `areacols` option for `Chart()`
or with `Chart.area()` with the `cols` option. As with `lines()` and `bars()`, the option can
be a `str` for a single column or an iterable of multiple column names.

An example is shown below.

```{python}
#| label: basics_areachart
#| fig-cap: "Generate bar chart data."
infilename = 'data/turkey_page4/fig4_chart1_exp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
linecol = 'Primary exp.'
areacols = list(df.columns)
areacols.remove(linecol)
```

```{python}
#| label: areachart
#| fig-cap: "Example area chart."
#| code-fold: show
# Create Chart object
chart1 = Chart(df, linecols=linecol, areacols=areacols,
               title='Central Government: Primary Expenditure Components',
               subtitle='(Percent of GDP)',
               xrange='2018-01:', yrange=[0, 30],
               ncol_legend=2)
chart1
```

The chart is identical to that of the chart for no options in the Bar chart gallery (@sec-basics-bars),
except that the stacked bars have been replaced with stacked areas.
Most of the options for area charts are the same as for bar charts, but to allow them to be specified together
when calling from `Chart()`, some input parameters are slightly different, for example the columns are
`areacols` when calling `Chart()` but `cols` when calling `Chart.area()`:
```python
Chart(df, areacols=cols)
```
and
```python
chart = Chart()
chart.area(data=df, cols=cols)
```

One further difference is that since area charts are expected to fill the entire x-axis range,
the `margins` are automatically set to 0 when an area graph is drawn.

Similar to `lines()` and `bars()`, the keyword `attrs` provides a way to control the attributes for each column.
Below are the options for an area graph, many are similar to that for bar graphs.

| Variable | Description |
|---|---|
| color | The color of bars for this column. |
| edgecolor | Edge colors of bars. |
| hatchcolor | Specify colors for any hatches |
| hatch | Specify a valid hatch specified [here](https://matplotlib.org/stable/gallery/shapes_and_collections/hatch_style_reference.html){target="_blank"} |
| hatchwidth | Specify hatch bar width |
| alpha | Apply transparency to color of area, specify as float between 0 and 1. |
| edgecolor | Specify color of lines for the edges of the bars. |
| legend | If `False`, do not add to legend. |

: {tbl-colwidths="[10,90]"}

All of these options are the same as for `bars()` except for `alpha`.

An example with customized area attrs is below.

```{python}
#| label: area_custom
#| fig-cap: "Customized area chart."

infilename = 'data/turkey_page5/fig5_chart6_gross_international_reserves.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
df.dropna(axis=0, how='all', inplace=True)

# Create Chart object
gircol = 'Gross International Reserves (GIR) (rhs)'
attrs = {gircol : {'color' : '#416FA6'},
         'Gold'  : {'color' : '#CAEDFE',
                   'hatch' : 'blue',
                   'hatch' : '\\\\',
                   'hatchwidth' : 2,
                   'edgecolor' : 'brown',
                   'alpha' : 0.3},
         'FX'    : {'color' : '#009CDE',
                    'hatchcolor' : 'red',
                    'hatch' : '////',
                    'hatchwidth' : 3,
                    'edgecolor' : 'purple'},
        }

chart = Chart(df, linecols=gircol,
              areacols=['FX', 'Gold'],
              attrs=attrs,
              title='Area chart',
              xrange='2022-01:', yrange=[-0.5, 200])
```

Internally, area graphs are created with the function `chart.area()`. As with `lines()` and `bars()`, the attributes of each area
are determined in the order of

1. Style options
2. Class-level options specified either when calling `Chart()` or `Chart.bars()`
3. Individual column level using `attrs`.

| Argument | Default | Description |
|---|---|---|
| data | None | Data to use, in the form of a `pandas.DataFrame`. If no data is specified, will try to use any data that was previously specified to create this chart |
| cols | None | The columns in the data to be charted as lines. Note that when calling `Chart()`, this option is `areacols` to distinguish from columns for lines and bars. An iterable of column names, or if a single column can use a `str`.|
| indexcol | None | By default the input `pandas.DataFrame`'s index is used as the x-axis. If this is a column in the DataFrame, specify using this option. |
| axis | None | Specify which y-axis to plot on. Note that when calling `Chart()` this is specified as `areaaxis` |
| stack | True | Specify whether to stack bars. If `True`, all bars are stacked on top of each other (default), otherwise they are staggered. when calling `Chart()` this is specified as `areastack`. |
| linewidth |None | Width of edges of bars. When calling `Chart()` this is specified as `arealinewidth`. |
| edgecolor | None | Edge color for bars. If not specified defaults to style default (black for Article IV). When calling `Chart()` this is specified as `areaedgecolor`. |
| attrs | None | Attributes for individual columns. |
| xrange | None | Specify x-axis range. See @sec-basics-format_axes. |
| margins | None | If specified, set how additional margins are added. Default is 'auto' which will automatically adjust. Can also specify number of days as integers. |
| xformat | None | Specify how x-axis is formatted for a time series plot. Default is to check the frequency of the data and automatically determine. Otherwise specify a frequency like 'D', 'W', 'M', 'Q', 'A' for daily, weekly, monthly, quarterly or annual frequency. |
| yrange | None | Override existing `yrange` of this object and set y-axis range |
| ryrange | None | Override existing `ryrange` of this object and set right y-axis range |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

Again, note that many options are the same as for `Chart.lines()` and especially `Chart.bars()`, so that switching
between bars and area graphs based on aesthetics is easy to do.
Below is a gallery of area charts with various options.

```{python}
#| label: area_data
infilename = 'data/turkey_page5/fig5_chart6_gross_international_reserves.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
df.dropna(axis=0, how='all', inplace=True)

# Create Chart object
gircol = 'Gross International Reserves (GIR) (rhs)'
areacols = ['FX', 'Gold']
```

::: {.panel-tabset}

### No options (Article IV style)

No options are passed in.
For area charts the margins are by default set to 0 so there is no space outside the plotted range.

```{python}
#| label: gallery_area_nooptions
#| fig-cap: "No options"
#| code-fold: show
# Create Chart object
chart = Chart(df, areacols=areacols,
              title='no options')
chart	      
```

### Color cycle

A color cycle is provided of red, green, blue.
Note that the first two colors are used for the area graphs,
and the third color blue is then used for the line.

```{python}
#| label: gallery_area_colors
#| fig-cap: "Color cycle"
#| code-fold: show
# Create Chart object
chart = Chart(df, linecols=gircol, areacols=areacols,
              colors=['red', 'green', 'blue'],
              title='color cycle')
chart
```

### Axis Right

The area chart is drawn on the right.
Since no y-axis range is specified for either the left or right y-axis,
the ranges do not agree exactly.

```{python}
#| label: gallery_area_axis_right
#| fig-cap: "Axis right."
#| code-fold: show
chart1 = Chart(df, linecols=gircol, areacols=areacols,
               title='axis right',
               areaaxis='right',
               ncol_legend=2)
```

### Area Edge Color/Width

In the below `areaedgecolor` is set to `'gold'` and the edge line width is given with `arealinewidth=3`.

```{python}
#| label: gallery_area_edges
#| fig-cap: "Edge color and width."
#| code-fold: show
chart1 = Chart(df, linecols=gircol, areacols=areacols,
               title='area edges',
               areaedgecolor='gold',
               arealinewidth=3,
               xrange='2022-01:', yrange=[0, 200],
               ncol_legend=2)
```

### Attributes

In the below a `dict` called `attrs` is passed in to specify the colors of each area.

```{python}
#| label: gallery_area_attrs
#| fig-cap: "Specify attributes."
#| code-fold: show
attrs = {gircol : {'color' : '#416FA6'},
         'FX' : {'color' : 'yellow',
                 'hatchcolor' : 'red',
                 'hatch' : '////',
                 'hatchwidth' : 3,
                 'edgecolor' : 'purple'},
         'Gold' : {'color' : 'grey',
                   'hatch' : 'blue',
                   'hatch' : '\\\\',
                   'hatchwidth' : 2,
                   'edgecolor' : 'brown',
                   'alpha' : 0.3}
         }

# Create Chart object
chart1 = Chart(df, linecols=gircol, areacols=areacols,
               title='attrs',
               attrs=attrs,
               xrange='2022-01:', yrange=[0, 200],
               ncol_legend=2)
```

### Add Area From a `dict`

In the below the function `area()` is called with a `dict` which is passed in as `**kwargs**`.

```{python}
#| label: gallery_area_kwargs
#| fig-cap: "Create from `dict`."
#| code-fold: show
chart1 = Chart(title='kwargs',
               xrange='2022-01:', yrange=[0, 200],
               ncol_legend=2)

attrs = {linecol : {'linewidth' : 4, 'color' : IMFBLACK},
         'Personnel' : {'color' : '#004C97'},
         'Goods & services' : {'color' : '#009CDE'},
         'Current transfers' : {'color' : '#CAEDFE'},
         'Capital exp.' : {'color' : '#FF8200'},
         'Other' : {'color' : '#DA291C'},                         
         }

# Add area using dict
kwargs = {'data' : df,
          'cols' : areacols,
          'attrs' : attrs,
          }
chart1.area(**kwargs)
```

### Unstacked

In the below the option `stack=False` is passed in.
To make the area graphs easier to see, `alpha=0.3` is also set for all areas.

```{python}
#| label: gallery_area_unstacked
#| fig-cap: "Unstacked."
#| code-fold: show
chart1 = Chart(df, linecols=gircol, areacols=areacols,
              colors=['red', 'yellow'],
	       alpha=0.3,
               areastack=False,
               title='stack=False',
               xrange='2022-01:', yrange=[0, 200],
               ncol_legend=2)
```

:::

## Add Horizontal/Vertical Lines and Rectangles {#sec-basics-lines_rects}

In many cases it is convenient to be able to add various auxiliary objects to a chart, such as horizontal, vertical lines and shaded areas (rectangles).
The `imfcharts` provides simple functions to add these.

```python
chart = Chart(df, linecols=linecols)

# Draw a horizontal line at y = 3
chart.hline(3)

# Draw a vertical line at x = 2020-03
chart.vline('2020-03')

# Draw a shaded target range between y = 0 and 1
chart.hrect(0, 1)

# Draw a shaded region between x = 2020-03 and 2021-06
chart.vrect('2020-03', '2021-06')
```

For horizontal lines and rectangles, the default is to span the entire width of the chart, these are useful for showing a target value or a target band.
For vertical lines and rectangles, the default is to span the entire height of the chart, these are useful for showing a specific date or category, or
a specific period (such as recessions). Under the hood, `hline` and `vline` use `Matplotlib`'s `ax.hline` and `ax.vline`, and `hrect` and `vrect` use
`ax.axhspan` and `ax.axvspan`.

Below are the options for each of these, and a gallery is provided with use cases.

### Horizontal Lines

Horizontal lines can be added to an existing `Chart` object with
```python
chart.hline(y)
```
which will draw a horizontal line at `y` across the entire chart.
Further options listed below allows customization.

| Argument | Default | Description |
|---|---|---|
|y       |      | Specify y position where line is drawn in coordinates of data being plotted. |
| xrange | None | Specify x-axis range for horizontal line. If `coordinates` is `'data'` for time series data, this converts the passed in `xrange` into coordinates of the chart. Otherwise the values are fractions of the chart from 0 to 1. |
| coordinates | 'data' | If this is `data` and the chart is plotting a time series, `xrange` will be interpreted as time ranges. |
| color | 'red' | Specify color of line, see sec-basics-misc-colors for valid colors. |
| linewidth |None | Width of edges of line. |
| linestyle | '-' | A valid `Matplotlib` line style specified [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"}. Special implementations such as "imfdash", "imfround" are implemented which mimic Excel styles. |
| alpha | 1 | Apply transparency to color of area, specify as float between 0 and 1. |
| dashes, dash_capstyle | None | Advanced options to specify cap styles |
| label | '' | When `legend` is `True`, a legend entry is created using this label.  |
| legend | `False` | If `False`, do not show this entry in the legend |
| zorder | 0 | Specify the drawing order, higher values are shown on top of other objects. |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

### Horizontal Rectangles

Horizontal rectangles (shades) have similar options as `hline` objects, a difference being that instead of one `y` value
one must specify two values of `ymin` and `ymax` of where the shade is drawn.

In the simplest case
```python
chart.hrect(0, 1)
```
will draw a shaded region between 0 and 1 in the data coordinates.
Additional options are below.

| Argument | Default | Description |
|---|---|---|
|ymin | 0 | Specify lower y position where shade is drawn in coordinates of data being plotted. |
|ymax | 0 | Specify higher y position where shade is drawn in coordinates of data being plotted. |
| xrange | None | Specify x-axis range for horizontal line. If `coordinates` is `'data'` for time series data, this converts the passed in `xrange` into coordinates of the chart. Otherwise the values are fractions of the chart from 0 to 1. |
| coordinates | 'data' | If this is `data` and the chart is plotting a time series, `xrange` will be interpreted as time ranges. |
| color | 'red' | Specify color of line, see sec-basics-misc-colors for valid colors. |
| linecolor | 'none' | Specify color of outline of shade. |
| linewidth | 0 | Width of edges of shade. |
| linestyle | None | A valid `Matplotlib` line style specified [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"}. Special implementations such as "imfdash", "imfround" are implemented which mimic Excel styles. |
| alpha | 0.3 | Apply transparency to color of area, specify as float between 0 and 1. |
| dashes, dash_capstyle | None | Advanced options to specify cap styles |
| hatch | None | Specify hatches to draw |
| label | '' | When `legend` is `True`, a legend entry is created using this label.  |
| legend | `False` | If `False`, do not show this entry in the legend |
| zorder | 0 | Specify the drawing order, higher values are shown on top of other objects. |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

### Vertical Lines

Horizontal lines can be added to an existing `Chart` object with
```python
chart.vline(x)
```
which will draw a vertical line at `x` for the entire chart.
Further options listed below allows customization.

| Argument | Default | Description |
|---|---|---|
|y       |      | Specify y position where line is drawn in coordinates of data being plotted. |
| yrange | None | Specify y-axis range for horizontal line. If `coordinates` is `'data'`, this interprets the values as coordinates of the chart, otherwise the values are fractions of the chart from 0 to 1. |
| coordinates | 'data' | If this is `data`, `yrange` will be interpreted as coordinates of the chart, otherwise as fractions of the chart. |
| color | 'red' | Specify fill color of shade, see sec-basics-misc-colors for valid colors. |
| linewidth | 1 | Width of edges of line. |
| linestyle | '-' | A valid `Matplotlib` line style specified [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"}. Special implementations such as "imfdash", "imfround" are implemented which mimic Excel styles. |
| alpha | 1 | Apply transparency to color of area, specify as float between 0 and 1. |
| dashes, dash_capstyle | None | Advanced options to specify cap styles |
| label | '' | When `legend` is `True`, a legend entry is created using this label.  |
| legend | `False` | If `False`, do not show this entry in the legend |
| zorder | 0 | Specify the drawing order, higher values are shown on top of other objects. |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

### Vertical Shades

Vertical rectangles (shades) have similar options as `hrect` objects, a difference being that instead of one `y` value
one must specify two values of `ymin` and `ymax` of where the shade is drawn.

In the simplest case
```python
chart.vrect(0, 1)
```
will draw a shaded region between 0 and 1 in the data coordinates.
Additional options are below.

| Argument | Default | Description |
|---|---|---|
|ymin | 0 | Specify lower y position where shade is drawn in coordinates of data being plotted. |
|ymax | 0 | Specify higher y position where shade is drawn in coordinates of data being plotted. |
| yrange | None | Specify y-axis range for horizontal line. If `coordinates` is `'data'`, this interprets the values as coordinates of the chart, otherwise the values are fractions of the chart from 0 to 1. |
| coordinates | 'data' | If this is `data`, `yrange` will be interpreted as coordinates of the chart, otherwise as fractions of the chart. |
| color | 'red' | Specify color of line, see sec-basics-misc-colors for valid colors. |
| linecolor | 'none' | Specify color of outline of shade. |
| linewidth |0 | Width of edges of shade. |
| linestyle | '-' | A valid `Matplotlib` line style specified [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"}. Special implementations such as "imfdash", "imfround" are implemented which mimic Excel styles. |
| alpha | 0.3 | Apply transparency to color of area, specify as float between 0 and 1. |
| dashes, dash_capstyle | None | Advanced options to specify cap styles |
| hatch | None | Specify hatches to draw |
| label | '' | When `legend` is `True`, a legend entry is created using this label.  |
| legend | `False` | If `False`, do not show this entry in the legend |
| zorder | 0 | Specify the drawing order, higher values are shown on top of other objects. |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

Below is a gallery showing how to add lines and shades.

::: {.panel-tabset}

```{python}
#| label: gallery_lines_rects_data

infilename = 'data/turkey_page2/fig2_chart1_inflation.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
```

### No options

No options are passed in for the `hline`, `vline`, `hrect` or `vrect`.

```{python}
#| label: gallery_lines_rects_nooptions
#| fig-cap: "No options"
#| code-fold: show
chart1 = Chart(df, linecols=df.columns, attrs=attrs,
               title='no options',
               xrange='2017-01:', yrange=[0, 120])

# Add hline
chart1.hline(y=20)

# Add vline
chart1.vline(x='2018-03')

# Add hrect
chart1.hrect(ymin=40, ymax=60)

chart1.vrect(xmin='2020-03', xmax='2022-06')
```

### Plot Options

Various plot options are passed into the  `hline`, `vline`, `hrect` and `vrect` objects.

```{python}
#| label: gallery_lines_rects_options
#| fig-cap: "With options"
#| code-fold: show
chart1 = Chart(df, linecols=df.columns, attrs=attrs,
               title='with options',
               xrange='2017-01:', yrange=[0, 120])

# Add hline
chart1.hline(y=20, xrange='2020-03:2025-04',
             color='blue', linewidth=1.5, linestyle='--', alpha=0.8)

# Add vline
chart1.vline(x='2018-03', yrange=[30, 100],
             color='green', linewidth=1.5, linestyle='--', alpha=0.8)

# Add hrect
chart1.hrect(ymin=40, ymax=60, xrange='2020-03:2025-04',
             hatch='\\\\', color='yellow', linewidth=1.5, linecolor='orange', linestyle='--', alpha=0.3)

chart1.vrect(xmin='2020-03', xmax='2022-06', yrange=[30, 60],
             hatch='//', color='blue', linewidth=1.5, linecolor='purple', linestyle='dotted', alpha=0.3)
```

### zorder, Legend Entry

The `zorder` of each `hline`, `vline`, `hrect` and `vrect` object are set to 5 so that they are above the data lines,
and a legend entry is added for each object.

```{python}
#| label: gallery_lines_rects_zorder
#| fig-cap: "zorder, legend"
#| code-fold: show
chart1 = Chart(df, linecols=df.columns, attrs=attrs,
               title='zorder, legend',
               xrange='2017-01:', yrange=[0, 120])

# Add hline
chart1.hline(y=20, xrange='2020-03:2025-04',
             color='blue', linewidth=1.5, linestyle='--', alpha=0.8,
             zorder=5, label='target', legend=True)

# Add vline
chart1.vline(x='2018-03',
             color='blue', linewidth=1.5, linestyle='--', alpha=0.8,
             zorder=5, label='reference period', legend=True)

# Add hrect
chart1.hrect(ymin=40, ymax=60,
             hatch='\\\\', color='yellow', linewidth=1.5, linecolor='orange', linestyle='--', alpha=0.2,
             zorder=5, label='target band', legend=True)

chart1.vrect(xmin='2020-01', xmax='2021-10',
             hatch='//', color='blue', linewidth=1.5, linecolor='purple', linestyle='--', alpha=0.4,
             zorder=5, label='stable period', legend=True)
```

### Creating with `dict`

Each `hline`, `vline`, `hrect` and `vrect` object is created using a `dict` as input.

```{python}
#| label: gallery_lines_rects_kwargs
#| fig-cap: "Using `dict`"
#| code-fold: show
chart1 = Chart(df, linecols=df.columns, attrs=attrs,
               title='create with dict',
               xrange='2017-01:', yrange=[0, 120])

# Add hline
kwargs = {'y' : 20, 'xrange' : '2020-03:2025-04',
          'label' : 'horizontal line', 'legend' : True,
          'color' : 'grey', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.8}
chart1.hline(**kwargs)

# Add vline
kwargs = {'x' : '2020-03', 'yrange' : [30, 60],
          'label' : 'vertical line', 'legend' : True,
          'color' : 'grey', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.8}
chart1.vline(**kwargs)

# Add hrect
kwargs = {'ymin' : 80, 'ymax' : 100,
          'hatch' : '++',
          'label' : 'horizontal rectangle', 'legend' : True,
          'color' : 'grey', 'linecolor' : 'skyblue', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.8}
chart1.hrect(**kwargs)

# Add vrect
kwargs = {'xmin' : '2022-01', 'xmax' : '2023-01',
          'hatch' : '////',
          'label' : 'vertical rectangle', 'legend' : True,
          'color' : 'pink', 'linecolor' : 'red', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.8}
chart1.vrect(**kwargs)
```

### Adding Directly in `Chart()`

Each `hline`, `vline`, `hrect` and `vrect` object is added to `Chart()` using a `list` of `dict`s.

```{python}
#| label: gallery_lines_rects_chart
#| fig-cap: "Adding directly in `Chart()`"
#| code-fold: show

# dicts for each object
kwargs_hline1 = {'y' : 10,
                 'label' : 'low horizontal line', 'legend' : True,
                 'color' : 'grey', 'linewidth' : 1.5, 'linestyle' : '--', 'alpha' : 0.7}

kwargs_hline2 = {'y' : 110,
                 'label' : 'high horizontal line', 'legend' : True,
                 'color' : 'blue', 'linewidth' : 1.5, 'linestyle' : '-', 'alpha' : 0.7}

kwargs_vline = {'x' : '2020-03',
                'label' : 'vertical line', 'legend' : True,
                'color' : 'red', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.7}

kwargs_hrect = {'ymin' : 80, 'ymax' : 100,
                'hatch' : '++',
                'label' : 'horizontal rectangle', 'legend' : True,
                'color' : 'yellow', 'linecolor' : 'red', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.7}

kwargs_vrect = {'xmin' : '2024-01', 'xmax' : '2024-05',
                'hatch' : '//',
                'label' : 'vertical rectangle', 'legend' : True,
                'color' : 'green', 'linecolor' : 'blue', 'linewidth' : 0.5, 'linestyle' : '--', 'alpha' : 0.7}

# Create `Chart` using kwargs of each object
chart1 = Chart(df, linecols=df.columns, attrs=attrs,
               title='zorder, legend',
               xrange='2017-01:', yrange=[0, 120],
               hlines=[kwargs_hline1, kwargs_hline2],
               vlines=[kwargs_vline],
               hrects=[kwargs_hrect],
               vrects=[kwargs_vrect])
```

:::


## Add Text, Arrows, Fill

Similar to horizontal/vertical lines and shades, text, arrows and fill reigons can be specified.
Below is an example of

```{python}
#| label: text_arrow_fill_data
#| fig-cap: "Chart with text, arrow, fill."

infilename = 'data/turkey_page1/fig1_chart1_gdp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
linecol = cols[0]

# Create a forecast for the next 4 quarters
p = df.index.max() + 3 * pd.offsets.MonthBegin()
lastval = df.loc[df.index.max(), linecol]
dates = pd.date_range(start=p, freq='3MS', end=p + pd.Timedelta(days=600))
for idate, date in enumerate(dates):
    forecast = lastval + 0.5 + np.random.normal(scale=0.3)
    df.loc[date, 'forecast'] = forecast
    df.loc[date, 'lower']    = forecast - 1.5 - (0.3 + 0.8 * idate) * np.random.random()
    df.loc[date, 'higher']   = forecast + 1.5 + (0.3 + 0.8 * idate) * np.random.random()
```

```{python}
#| label: text_arrow_fill
#| fig-cap: "Example of text, arrow, fill"
#| code-fold: show
attrs = {linecol : {'linewidth' : 4, 'color' : '#004C97',
                    'marker' : 'o', 'markersize' : 10,
                    'markerfacecolor' : 'white', 'markeredgewidth' : 4,
                    'markeredgecolor' : '#004C97'},
         'forecast' : {'marker' : 'x',
                       'markersize' : 12,
                       'linestyle' : '--',
                       'linewidth' : 0.8,
                       'color' : 'red'}
         }

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               attrs=attrs,
               title='Contributions to Real GDP Growth',
               xrange='2023Q1:', yrange=[-5, 9.5])

# Add hline
chart1.hline(y=1.4, xrange='2023Q1:' + df.index[-1].strftime('%Y-%m'),
             color=IMFBLACK, linewidth=2.5, linestyle='--', dashes=[10, 4])

# Add fill for two columns in data.
chart1.fill('lower', 'higher')

# Add text
text = '''Real GDP growth\nlong-run average\n(1.4 q/q)'''
chart1.text(pd.Timestamp('2024Q3'), 6.5, text=text, fontweight='bold', color='#004C97')

# Add arrow
chart1.arrow(head=[pd.Timestamp('2025Q1'), 1.5], tail=[pd.Timestamp('2025Q1'), 5],
             color='#004C97')
```

The syntax is straightforward, text is added by specifying the x, y coordinates as well as the text to show.
Arrows need coordinates for a head and a tail. Fill is added by specifying columns of a `pandas.DataFrame` that
specify the region to be filled. For all of these, the usual attributes such as `color` etc. can be specified.
Internally, text is added with `Matplotlib`'s `ax.text()`, arrows are added with `ax.annotate()`,
and fill is added with `ax.fill_between()`.

The options available for `text()` are below.

| Argument | Default | Description |
|---|---|---|
| x | | x coordinate of text. |
| y | | y coordinate of text. |
| text | '' | The text to be shown. |
| color | 'black' | Color of text |
| fontsize | 14 | Font size of text |
| fontfamily | 'Segoe UI' | Text font |
| fontweight | 'normal' | Choose font weight from [options](https://matplotlib.org/stable/users/explain/text/text_props.html){target="_blank"} available |
| va | 'top' | Vertical alignment of text |
| ha | 'left' | Horizontal alignment of text |
| zorder | 1 | Specify the drawing order, higher values are shown on top of other objects. |

: {tbl-colwidths="[10,10, 80]"}

The options available for `arrow()` are below.

| Argument | Default | Description |
|---|---|---|
| 'head' | `(0, 0)` | Head position of arrow. |
| 'tail' | `(0, 0)` | Tail position of arrow. |
| color | 'black' | Color of arrow |
| headwidth | 15 | Width of arrow head |
| headlength | 15 | Length of arrow head |
| edgecolor | `None` | Edge color of arrow |
| edgewidth | 0 | Edge width of arrow |
| va | 'top' | Vertical alignment of text |
| ha | 'left' | Horizontal alignment of text |
| coords | 'data' |Coordinates of `head` and `tail`. Can specify `'axes fraction'` instead of `'data'` if setting position irrespective of charting data. |
| zorder | 1 | Specify the drawing order, higher values are shown on top of other objects. |

: {tbl-colwidths="[10,10, 80]"}

The options available for `fill` are below.

| Argument | Default | Description |
|---|---|---|
| lo |  | Column name in data for the lower bound of filled area. |
| hi |  | Column name in data for the higher bound of filled area. |
| data | None | Data to use, in the form of a `pandas.DataFrame`. If no data is specified, will try to use any data that was previously specified to create this chart |
| indexcol | None | By default the input `pandas.DataFrame`'s index is used as the x-axis. If this is a column in the DataFrame, specify using this option. |
| axis | 'left' | Specify which y-axis to plot on |
| color | 'red' | Color of arrow |
| linecolor |'none' | Color of edges. |
| linewidth |0 | Width of edges. |
| linestyle |'-' | Line style of edges, specify a [valid line style](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html){target="_blank"} |
| alpha | 0.3 | Apply transparency to color of area, specify as float between 0 and 1. |
| dashes, dash_capstyle | Advanced options to specify cap styles |
| label | '' | When `legend` is `True`, a legend entry is created using this label.  |
| legend | `False` | If `False`, do not show this entry in the legend |
| zorder | 0 | Specify the drawing order, higher values are shown on top of other objects. |
| xrange | None | Specify x-axis range for horizontal line. If `coordinates` is `'data'` for time series data, this converts the passed in `xrange` into coordinates of the chart. Otherwise the values are fractions of the chart from 0 to 1. |
| margins | None | If specified, set how additional margins are added. Default is 'auto' which will automatically adjust. Can also specify number of days as integers. |
| xformat | None | Specify how x-axis is formatted for a time series plot. Default is to check the frequency of the data and automatically determine. Otherwise specify a frequency like 'D', 'W', 'M', 'Q', 'A' for daily, weekly, monthly, quarterly or annual frequency. |
| yrange | None | Override existing `yrange` of this object and set y-axis range |
| ryrange | None | Override existing `ryrange` of this object and set right y-axis range |
| debug | False | Show information when running. |

: {tbl-colwidths="[10,10, 80]"}

Below is a gallery of various options to add text, arrow, and fills.

```{python}
#| label: text_arrow_fill_data2
#| fig-cap: "Chart with text, arrow, fill."

infilename = 'data/turkey_page1/fig1_chart1_gdp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])
cols = df.columns
linecol = cols[0]

# Create a forecast for the next 4 quarters
p = df.index.max() + 3 * pd.offsets.MonthBegin()
lastval = df.loc[df.index.max(), linecol]
dates = pd.date_range(start=p, freq='3MS', end=p + pd.Timedelta(days=600))
for idate, date in enumerate(dates):
    forecast = lastval + 0.5 + np.random.normal(scale=0.3)
    df.loc[date, 'forecast'] = forecast
    df.loc[date, '25%'] = forecast - 1.5 - (0.3 + 0.8 * idate) * np.random.random()
    df.loc[date, '75%'] = forecast + 1.5 + (0.3 + 0.8 * idate) * np.random.random()
    df.loc[date, '10%'] = forecast - 4.5 - (0.3 + 0.5 * idate) * np.random.random()
    df.loc[date, '90%'] = forecast + 4.5 + (0.3 + 0.5 * idate) * np.random.random()
```

::: {.panel-tabset}

### No options

```{python}
#| label: gallery_text_arrow_fill_nooptions
#| fig-cap: "No options"
#| code-fold: show

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               title='No options',
               xrange='2023Q1:', yrange=[-5, 9.5])

# Add hline
chart1.hline(y=1.4)

# Add fill for two columns in data.
chart1.fill('25%', '75%')

# Add text
text = '''Real GDP growth\nlong-run average\n(1.4 q/q)'''
chart1.text(pd.Timestamp('2024Q3'), 6.5, text=text)

# Add arrow
chart1.arrow(head=[pd.Timestamp('2025Q1'), 1.5], tail=[pd.Timestamp('2025Q1'), 5])
```

### With Options

In the below each object is multiple attributes set.
Notice that for `arrow()` the `coords='axes fraction'` so that the `head` and `tail`
are specified in coordinates of the axes where the bottom left is (0, 0) and the top right is (1, 1).

```{python}
#| label: gallery_text_arrow_fill_options
#| fig-cap: "With options"
#| code-fold: show

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               title='With options',
               xrange='2023Q1:', yrange=[-5, 9.5])

# Add hline
chart1.hline(y=1.4, xrange='2023Q1:' + df.index[-1].strftime('%Y-%m'),
             color=IMFGREEN, linewidth=2.5, linestyle='-.', dashes=[10, 4])

# Add fill for two columns in data.
chart1.fill('25%', '75%', color='yellow', alpha=0.3, linecolor='orange', linewidth=1.5, linestyle='--')

# Add text
text = '''Real GDP growth\nlong-run average\n(1.4 q/q)'''
chart1.text(pd.Timestamp('2024Q3'), 6.5, text=text, fontsize=10, fontfamily='monospace', fontweight='bold')

# Add arrow
chart1.arrow(head=[pd.Timestamp('2025Q1'), 1.5],
             tail=[pd.Timestamp('2025Q1'), 5],
             color='#004C97',
             edgecolor='red', edgewidth=1,
             width=6, headwidth=7, headlength=20)
```

### Coordinates in `'axes fraction'`

In the below each object is multiple attributes set.
For `arrow()` we set `coords='axes fraction'` so that the `head` and `tail`
are specified in coordinates of the axes where the bottom left is (0, 0) and the top right is (1, 1).
This allows adding the arrow irrespective of the data being charted.

```{python}
#| label: gallery_text_arrow_fill_axesfraction
#| fig-cap: "Axes fractions"
#| code-fold: show

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               title='Specify position with "axes fraction"',
               xrange='2023Q1:', yrange=[-5, 9.5])

# Add hline
chart1.hline(y=1.4, xrange='2023Q1:' + df.index[-1].strftime('%Y-%m'),
             color=IMFGREEN, linewidth=2.5, linestyle='-.', dashes=[10, 4])

# Add fill for two columns in data.
chart1.fill('25%', '75%', color='yellow', alpha=0.3, linecolor='orange', linewidth=1.5, linestyle='--')

# Add text
text = '''Real GDP growth\nlong-run average\n(1.4 q/q)'''
chart1.text(pd.Timestamp('2024Q3'), 6.5, text=text, fontsize=14, fontfamily='monospace', fontweight='bold')

# Add arrow
chart1.arrow(head=[0.60, 0.5], tail=[0.60, 0.6], coords='axes fraction',
             width=6, headwidth=7, headlength=20)
```

### Arrow Options

Each `arrow` that spans a year each is accompanied by `text` displaying its options.
The default is to use `width=4, headwidth=15, headlength=15, shrink=0.05`
so that the arrow is shrunk by 5% to the specified `head` and `tail`.
Other arrows demonstrate setting `shrink=0`, changing the `headwidth` and `headlength`,
and arrow width with `width`. For the rightmost blue arrow, `zorder=-1` is set so that
the arrow appears underneath the vertical lines.

```{python}
#| label: gallery_text_arrow_fill_arrowoptions
#| fig-cap: "Options for Arrows"
#| code-fold: show

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               title='arrow options',
               xrange='2023Q1:', yrange=[-5, 9.5])

# Add hline
chart1.hline(y=1.4, xrange='2023Q1:' + df.index[-1].strftime('%Y-%m'),
             color=IMFGREEN, linewidth=2.5, linestyle='-.', dashes=[10, 4])

# Add fill for two columns in data.
chart1.fill('25%', '75%', color='yellow', alpha=0.3, linecolor='orange', linewidth=1.5, linestyle='--')

# Add vertical lines at each year
for year in range(2023, 2027+1):
    chart1.vline(x=str(year)+'-01', color='red', alpha=0.7, linestyle='--')

# Add arrow
chart1.arrow(tail=['2023Q1', -4], head=['2024Q1', -4], coords='data')
chart1.text(pd.Timestamp('2023Q1'), -4.5, 'default',
            fontsize=6)
    
# Add arrow
chart1.arrow(tail=['2023Q1', -2], head=['2024Q1', -2], coords='data',
             color='pink', edgecolor='red', edgewidth=1, 
             width=1, headwidth=5, headlength=5, shrink=0)
chart1.text(pd.Timestamp('2023Q1'), -1.5, 'width=1, headwidth=5, headlength=5, shrink=0',
            fontsize=6)

# Add arrow
chart1.arrow(tail=['2024Q1', -2], head=['2025Q1', -2], coords='data',
             color='pink', edgecolor='yellow', edgewidth=1, 
             width=1, headwidth=15, headlength=5, shrink=0.05)
chart1.text(pd.Timestamp('2024Q1'), -2.5, 'width=1, headwidth=15, headlength=5, shrink=0.05',
            fontsize=6)

# Add arrow
chart1.arrow(tail=['2025Q1', -2], head=['2026Q1', -2], coords='data',
             color='pink', edgecolor='green', edgewidth=2,
             width=2, headwidth=5, headlength=15, shrink=0)
chart1.text(pd.Timestamp('2025Q1'), -1.5, 'width=2, headwidth=5, headlength=15, shrink=0',
            fontsize=6)

# Add arrow
chart1.arrow(tail=['2026Q1', -2], head=['2027Q1', -2], coords='data',
             color='pink', edgewidth=0,
             width=2, headwidth=5, headlength=15, shrink=0, zorder=-1)
chart1.text(pd.Timestamp('2026Q1'), -2.5, 'edgewidth=0, width=2, headwidth=5, headlength=15, shrink=0',
            fontsize=6)
```

### Multiple Bands

An example showing how to have multiple bands.

```{python}
#| label: gallery_text_arrow_fill_multiple
#| fig-cap: "Multiple Fills"
#| code-fold: show

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               title='Multiple bands',
               xrange='2023Q1:', yrange=[-5, 9.5])

# Add fill for 25-75 percentile
chart1.fill('25%', '75%', color='grey', alpha=0.7,
            label=r'$1 \sigma$', legend=True)

# Add fill between 10-25 percentile
chart1.fill('10%', '25%', color='grey', alpha=0.3,
            label=r'$2 \sigma$', legend=True)

# Add fill between 75-90 percentile
chart1.fill('75%', '90%', color='grey', alpha=0.3)
```

### Adding Directly in `Chart()` Using `dict`s

An example of how to add text, arrows, and fill directly in `Chart()`.
Each input is set up as a `dict` and passed in as a `list` of `dict`s to `Chart()`.

```{python}
#| label: gallery_text_arrow_fill_kwargs
#| fig-cap: "Using `dict` to add Text, Arrow, Fill"
#| code-fold: show

kw_hline = {'y' : 1.4, 'xrange' : '2020Q1:' + df.index[-1].strftime('%Y-%m'),
            'color' : IMFBLACK, 'linewidth' : 2.5, 'linestyle' : '--', 'dashes' : [10, 4]}


text = '''Real GDP growth
long-run average
(1.4 q/q)'''

kw_text = {'x' : pd.Timestamp('2024Q3'), 'y' : 6.5, 'text' : text,
           'fontweight' : 'bold', 'color' : '#004C97'}

kw_arrow = {'head' : [pd.Timestamp('2025Q1'), 1.5],
            'tail' : [pd.Timestamp('2025Q1'), 5],
            'color' : '#004C97'}

kw_fills_mid = {'lo' : '25%', 'hi' : '75%',
                'color' : 'grey', 'alpha' : 0.7,
                'label' : r'$1 \sigma$', 'legend' : True}

kw_fills_lo = {'lo' : '10%', 'hi' : '25%',
                'color' : 'grey', 'alpha' : 0.3,
                'label' : r'$2 \sigma$', 'legend' : True}

kw_fills_hi = {'lo' : '75%', 'hi' : '90%',
                'color' : 'grey', 'alpha' : 0.3}

chart1 = Chart(df, linecols=[linecol, 'forecast'],
               hlines=[kw_hline], # Add hline via kwargs
               texts = [kw_text], # Add text via kwargs
               arrows = [kw_arrow], # Add arrow via kwargs
               fills=[kw_fills_mid, kw_fills_lo, kw_fills_hi],
               title='dict inputs',
               xrange='2023Q1:', yrange=[-5, 9.5])
```

:::

## Additional Functions{#sec-basics-additional}

Further functions exist for customizing and manipulating charts.
In many cases the functions can be called directly as `Matplotlib` functions, and the underlying functions are shown below.
The reason these functions exist is so that the defualt behavior of any IMF charts can be automatically captured using these
so that users do not have to be aware of, or look into the underlying functions.

### Showing and Saving `Chart`

Once a `Chart` object is created, the following functions can be called on it:
```python
# Show chart on the screen
chart.show()

# Save the chart
chart.save('chart.pdf')
```

Note that the `Chart.show()` function attempts to saves the `Chart` object to a png file and shows it.
While `Matplotlib` `Figure` objects have a `show()` function, the output displayed can be different from
what is saved due to screen resolution, backend being used, and environment variables from different libraries.
Due to these complications, the `Chart.show()` function shows a saved png image which is what the user will get as output.

To save a `Chart`, specify the filename with appropriate extension, typically pdf or png.
Further options are

| Argument | Default | Description |
|---|---|---|
| dpi | 250 | Resolution for image, only affects png and other rastered images (not pdf). |
| bbox_inches | 'tight' | Tightly remove additional unused space from the image. |
| pad_inches | 0.02 | Padding, in inches around the image for white space. |

: {tbl-colwidths="[10,10, 80]"}

In most cases the defaults should provide good results.
There are no further options for `Chart.show()`. It is also possible to use the `Chart.save()` function
directly and open the resulting image.

### Adding Watermark

Watermarks can be added as semi-transparent text. A quick example is as follows

```{python}
#| label: watermark
#| fig-cap: "Adding watermark"
#| code-fold: show
infilename = 'data/turkey_page2/fig2_chart1_inflation.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

attrs = {'Inflation' : {'linewidth' : 4, 'color' : IMFBLACK},
         'Goods' : {'linewidth' : 4, 'color' : IMFBLUE, 'linestyle' : 'imfdash'},
         'Services' : {'linewidth' : 4, 'color' : IMFRED, 'linestyle' : 'imfdash'}}
linecols = df.columns

chart1 = Chart(df, linecols=linecols,
               attrs=attrs,
               title='Inflation: Goods and Services',
               subtitle='(Y/y percent change)',
               xrange='2017-01:', yrange=[0, 120],
               watermark='Confidential')
```

The watermark appears as semi-transparent text by specifying the parameter `watermark` when calling `Chart()`.
This is internally implemented with the function `Chart.watermark()` and options to call this from `Chart()` are listed below.

| Argument | Default | Description |
|---|---|---|
| watermark | None | The text to show in the watermark. When calling `Chart.watermark()` the argument is `text` and default is "Confidential". |
| wwx | 0.5 | X coordinates of the text in figure coordinates, that is 0 is the left edge of the `matplotlib.Figure` and 1 is the right edge. When calling `Chart.watermark()` the argument is `x`. |
| wmy | 0.5 | Y coordinates of the text in figure coordinates, that is 0 is the bottom edge of the `matplotlib.Figure` and 1 is the top edge. When calling `Chart.watermark()` the argument is `x`. |
| wmsize | 40 | Font size of watermark. When calling `Chart.watermark()` the argument is `size`.  |
| wmfont | None | Font size of watermark. When calling `Chart.watermark()` the argument is `font`. Defaults to `matplotlib.rcParams["font.family"]` if not specified.  |
| wmcolor | 'gray' | Font color of watermark. When calling `Chart.watermark()` the argument is `color`. Defaults to 'gray' if not specified.  |
| wmalpha | 0.3 | Font transparency of watermark. When calling `Chart.watermark()` the argument is `alpha`. |
| wmangle | 30 | Angle of watermark. When calling `Chart.watermark()` the argument is `angle`. |
| zorder | 10 | Specify the drawing order, higher values are shown on top of other objects. Set to 0 to show behind all other objects. |

: {tbl-colwidths="[10,10, 80]"}

Watermarks can also be added later, below is an example.

```{python}
#| label: watermark_later
#| fig-cap: "Adding watermark later"
#| code-fold: show
infilename = 'data/turkey_page2/fig2_chart1_inflation.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

attrs = {'Inflation' : {'linewidth' : 4, 'color' : IMFBLACK},
         'Goods' : {'linewidth' : 4, 'color' : IMFBLUE, 'linestyle' : 'imfdash'},
         'Services' : {'linewidth' : 4, 'color' : IMFRED, 'linestyle' : 'imfdash'}}
linecols = df.columns

chart1 = Chart(df, linecols=linecols,
               attrs=attrs,
               title='Inflation: Goods and Services',
               subtitle='(Y/y percent change)',
               xrange='2017-01:', yrange=[0, 120])
chart1.watermark(text='Confidential', x=0.3, y=0.3, angle=45, size=30, color='blue', alpha=0.7, zorder=0)
```


### Adding Titles, Subtitles

The `Chart()` function has arguments `title` and `subtitle` which allow specifying titles and subtitles, respectively.
Internally these call `Chart.title()` and `Chart.subtitle()` but have similar options.
The `imfcharts` library is set up so that by using the default arugments the titles should appear correctly for each publication type,
and in general it should only be necessary to specify the text.

The simplest way to set a title and subtitle are when creating the chart:

```{python}
#| label: basics_additional_title
#| fig-cap: "Specifying title, subtitle"
#| code-fold: show
infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

chart = Chart(df, linecols=df.columns,
              title='Monetary Policy Rate', subtitle='(Percent)',
              colors=['red', 'green', 'blue'], linewidth=3,
              xrange='2023-01:', yrange=[0, 90])
```

Options for setting the title are below.

| Argument | Default | Description |
|---|---|---|
| text | None | The title to be shown. When calling `Chart()` this is `title`. |
| color | 'black' | Color of title. When calling `Chart()` this is `titlecolor`. |
| fontsize | 14 | Font size of title. When calling `Chart()` this is `titlefontsize`. |
| font | 'Segoe UI' | Title font. When calling `Chart()` this is `titlefont`. |
| fontweight | 'normal' | Choose font weight from [options](https://matplotlib.org/stable/users/explain/text/text_props.html){target="_blank"} available. When calling `Chart()` this is `titlefontweight`. |
| loc | None | Horizontal alignment of title. When calling `Chart()` this is `titleloc`. |
| y |1.05 | y coordinate of text. When calling `Chart()` this is `titley`. |

: {tbl-colwidths="[10,10, 80]"}

The title can be set after the `Chart` object is created with
```python
chart.title(title)
```
and any of the options above.

Options for setting the subtitle are below.

| Argument | Default | Description |
|---|---|---|
| text | None | The subtitle to be shown. When calling `Chart()` this is `subtitle`. |
| color | 'black' | Color of subtitle. When calling `Chart()` this is `subtitlecolor`. |
| fontsize | 14 | Font size of subtitle. When calling `Chart()` this is `subtitlefontsize`. |
| font | 'Segoe UI' | Subtitle font. When calling `Chart()` this is `subtitlefont`. |
| fontweight | 'normal' | Choose font weight from [options](https://matplotlib.org/stable/users/explain/text/text_props.html){target="_blank"} available. When calling `Chart()` this is `subtitlefontweight`. |
| ha | None | Horizontal alignment of subtitle. When calling `Chart()` this is `subtitleha`. |
| va | None | Vertical alignment of subtitle. When calling `Chart()` this is `subtitleva`. |
| y |1.03 | y coordinate of text. When calling `Chart()` this is `subtitley`. |

: {tbl-colwidths="[10,10, 80]"}

The subtitle can be set after the `Chart` object is created with
```python
chart.subtitle(subtitle)
```
and any of the options above.

### Adding Axes Labels

Axes labels (titles) can be set within `Chart()` with arguments `xtitle` and `yttile`, along with various arguments for customization.
Internally these call `Chart.xtitle(xtitle)` and `Chart.ytitle(ytitle)`, which rely on the `Matplotlib` functions
`ax.set_xlabel()` and `ax.set_ylabel()`.

The options for `xtitle()` and `ytitle()` are below.

| Argument | Default | Description |
|---|---|---|
| text | None | The text to be shown. When calling `Chart()` this is `xtitle` and `ytitle`. |
| fontsize | 14 | Font size. When calling `Chart()` this is `xfontsize` and `yfontsize`. |
| font | 'Segoe UI' | Text font. When calling `Chart()` this is `xfont` and `yfont`. |
| fontweight | 'normal' | Choose font weight from [options](https://matplotlib.org/stable/users/explain/text/text_props.html){target="_blank"} available. When calling `Chart()` this is `xfontweight` and `yfontweight`. |
| color | 'black' | Color of text. When calling `Chart()` this is `xcolor` and `ycolor`. |
| pad | 8 | Padding between axis and label. When calling `Chart()` this is `xpad` and `ypad`. |
| loc | 'left'/'center' | Location of label, left for x-axis, center for y-axis. When calling `Chart()` this is `xloc` and `yloc`. |
| rotation | 0/90 | Rotation of label. When calling `Chart()` this is `xrotation` and `yrotation`. |
| alpha |1 | Transparency of text. When calling `Chart()` this is `xalpha` and `yalpha`. |

: {tbl-colwidths="[10,10, 80]"}

Below is an example of customized x-axis and y-axis labels.

```{python}
#| label: basics_axis_titles
#| fig-cap: "Specifying x-axis and y-axis titles"
#| code-fold: show

infilename = 'data/turkey_page2/fig2_chart3_mp.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0])

chart = Chart(df, linecols=df.columns,
              title='Examples of X-axis and Y-axis Titles',
              subtitle='(Percent)',
              xtitle='dates',
              xfontsize=10, xfont='monospace', xfontweight='bold', xcolor='red', xpad=2, xloc='center', xrotation=30, xalpha=0.3,
              ytitle='values',
              yfontsize=10, yfont='monospace', yfontweight='bold', ycolor='blue', ypad=2, yloc='top', yrotation=75, yalpha=0.3,
              xrange='2023-01:', yrange=[0, 90])
```

### Legend Options

The legend is by default set automatically to be shown.
Internally, this is set with the function `legend()` which takes on various options for customization.
To turn off the existing legend, call
```python
Chart(legend=False)
```
or for an existing `Chart`, call
```python
chart.legend(show=False)
```
which will then delete the existing legend.

When adding new elements to a `Chart` object, it will always record which elemnts are added to the legend as an entry,
so even if a `Chart` is created with the legend turned off, once it is turned on it will correctly show all
entries that were specified. By default, lines, bars and areas will have legend entries added for each column
specified unless `legend=False` is passed into the attributes like
```python
chart.lines(data=df, cols='GDP', attrs={'GDP' : {'legend' : False}})
```
while for horizontal/vertical lines and shades as well as for filling between lines will not show a legend entry
unless `legend=True` is passed in explicitly:
```python
chart.hline(y=3, legend=True)
```

The options available for a legend are shown below.
All of these options can be passed directly into `Chart()` so that the properties are set for the `Chart` object.

| Argument | Default | Description |
|---|---|---|
| ncol_legend | 1 | Number of columns for the legend |
| legend_spacing | 0.5 | Vertical spacing between legend entries. |
| legend_fontsize | 14 | Font size of legend entries |
| legend_header | '' | Legend title |
| legend_header_color | 'black' | Legend title font color |
| legend_header_fontsize | 16 | Legend title font size |
| legend_left | 0.04 | Legend left position, axes coordinates (left edge 0, right edge 1) |
| legend_bottom | 0.85 | Legend bottom position, axes coordinates (bottom edge 0, top edge 1) |
| legend_width | 0.70 | Width of legend in axes coordinates |
| legend_height | 0.15 | Height of legend in axes coordinates |
| legend_mode | 'expand' | How legend expands, 'expand' will set it to expand as necessary |
| legend_frame | False | Whether to have a frame around the legend. |
| legend_color | 'white' | Legend background color |
| legend_alpha | 1 | Legend transparency |
| legend_shadow | False | Add a shadow to the legend |
| legend_fancybox | False | Whether the legend corners are rounded |
| legend_edge | 'black' | Legend edge line colors |
| legend_linestyle | '-' | Legend edge line style |
| legend_linewidth | 1 | Legend edge line width |

: {tbl-colwidths="[10,10, 80]"}

### Show Left or Right Y-axis on Top

In some cases the user may want to specify which of the objects drawn on the left and right y-axes should
be shown on top. The function
```python
chart.top_axis('right')
```
will set the objects drawn on the right y-axis to show up on top.
This can be reset to the default of having the left y-axis objects on top with
```python
chart.top_axis('left')
```

### Showing Additional Information

To show internal debugging messages, set `debug=True` for various functions, including `Chart()`
```python
chart =Chart(data=df, linecols=cols, debug=True)
chart.hline(y=3, debug=True)
```

### Formatting Axis Ranges {#sec-basics-format_axes}

Setting the axis range for the y-axes is straightforward.
In `Chart()` as well as functions that draw data like `lines()`, `bars()`, and `area()`,
pass in the argument `yrange=[ymin, ymax]` or `ryrange=[ymin, ymax]` and this will set
the axis range of the left or right y-axis, respectively.
Note that once the y-axis range is specified, this is recorded in the `Chart` object so that
unless this is further updated with another call to a function with the argument `yrange`,
the y-axis ranges will stay the same. A recommendation is to first create the chart without
specifying the y-axis range and let `Matplotlib` automatically adjust the axis ranges,
then for publication specify the range with "clean" numbers. Various examples of setting
`yrange` or `ryrange` have been provided in this documentation. Internally, the y-axis range
is changed with the functions `Chart.yrange([ymin, ymax])` and `Chart.ryrange([ymin, ymax])`.
```python
chart =Chart(data=df, linecols='GDP', rlinecols='Inflation')
chart.yrange([-2, 3])
chart.ryrange([0, 15])
```

Setting the x-axis range is a little more complicated as in many cases a time series is plotted,
and margins and formatting is based on the frequency and length of data.
The argument `xrange` can be passed into `Chart()` as well as functions that draw data - `lines()`, `bars()`, and `area()`.
If a time series is being plotted, `xrange` can be an iterable of length two that can be dates or `str`s that can be interpreted
as dates, or a `str` that has two dates separated by a colon (:). In the below, all are equivalent.

```python
# Specify as two dates
chart = Chart(df, linecols=col, xrange=[pd.Timestamp('2020-01'), pd.Timestamp('2025-01')])

# Specify as two strs that can be interpreted as dates
chart = Chart(df, linecols=col, xrange=['2020-01', '2025-01'])

# Specify a str with two dates separated by a :
chart = Chart(df, linecols=col, xrange='2020-01:2025-01')
```

When specifying a `str` with two dates separated a colon, if a date is abbreviated on one side,
the data passed in will determine the range for that side:
```python
# Set only starting range (all available data including and after 2020-01 shown)
chart = Chart(df, linecols=col, xrange='2020-01:')

# Set only ending range (all available data including and before 2025-01 shown)
chart = Chart(df, linecols=col, xrange=':2025-01')
```

In many cases it is useful to have margins around the start and end so that the data points can be clearly seen.
In all cases, when `xrange` can be specified, a further option `margins` can be specified as well.
This defualts to `'auto'` in which case the frequency of the data will determine the margins.
For each frequency of daily, weekly, monthly, quarterly and yearly data, the margins are 1, 5, 30, 85, 335 days, respectively.
Passing an integer value to `margins` will set the margin on both sides to be that many days.

```python
# Default, margins determined by frequency of data
chart = Chart(df, linecols=col, margins='auto')

# Specify margins with integer, will have 10 days of margins on both sides
chart = Chart(df, linecols=col, margins=10)
```

In cases where data is not time series data, the margins can be specified as floats.
If the data has an index of categorical data such as country names, by default if `margins` is `'auto'`
margins of 0.5 (half a category length) will be added. This can be modified by specifying `margins` with a number.
If the data has a numerical index, the default when `margins` is `'auto'` will be to add 3% margins around the total length of the data.
This can also be modified by passing in a float that corresponds to the margins (in fractions of the total index length).

```python
# By default for categorical and numerical index,
# margins of +/- 0.5 categories or 3% of the total will be added, respectively
chart = Chart(df, linecols=col, margins='auto')

# For categorical data index, specify margins as floats
chart = Chart(df, linecols=col, margins=1.2)

# For numerical data index, specify margins as floats as fraction of total length.
# 5% margins:
chart = Chart(df, linecols=col, margins=0.05)
```

Internally, the x-axis margins are called with the function
```python
chart.xrange(xrange, margins='auto')
```
which can be called at any time to modify the x-axis range.

For time series data, another complication is how to format the x-axis tick values.
When data is added to the chart via `Chart()`, `lines()`, `bars()`, `area()`,
by default the x-axis formatting is determined by the data frequency.
For each frequency the format is given as below.

| Frequency | Formatting | Example |
|---|---|---|
| daily | '%m/%d/%Y' | '2026-01-01' |
| weekly | '%m/%d/%Y' | '2026-01-01' |
| monthly | '%b-%y' | 'Jan-26' |
| quarterly | '%YQ%q' | '2026Q1' |
| annual | '%Y' | '2026-01-01' |

: {tbl-colwidths="[30,30,40]"}

The format can also be specified directly with the argument `xformat` which is provided for
`Chart()`, `lines()`, `bars()`, `area()`. This can either be a frequency (one of D, W, M, Q, A)
so that the formatting matches the frequency in the above table, or it can be specified as a
formatter like `'%Y-%m'`, which will show as values like '2026-01'.
See this [cheatsheet](https://strftime.org/){target="_blank"} for examples.

This can be specifed at any time with the function
```python
chart.xaxis_format(xformat)
```

The following gallery shows examples of setting the margins and x-axis formatting.

```{python}
#| label: basics_xaxis_data
infilename = 'data/turkey_page5/fig5_chart2_current_account_mms.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0]).dropna(how='all', axis=0)
```

::: {.panel-tabset}

### No options

No options are provided for the x-axis, so all available data is plotted,
and the x-axis is formatted to have the form `'%b-%Y'`.

```{python}
#| label: gallery_xaxis_nooptions
#| fig-cap: "Defaults"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
               title='No options',
               yrange=[-95, 60],
               legend_bottom=0.22)
```

### Specify x-axis range, margins

The x-axis range is specified along with margins, and the formatting is changed to '%Y-%m'.

```{python}
#| label: gallery_xaxis_options
#| fig-cap: "X-axis Options"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
               title='Specify xrange, margins, xformat',
               xrange='2022-01:', margins=90, xformat='%Y-%m',
               yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### Categorical Data

For categorical data the margins default to half a category length.

```{python}
#| label: gallery_xaxis_categorical
#| fig-cap: "Categorical Data"
#| code-fold: show

infilename = 'data/turkey_page5/fig5_chart3_terms_of_trade.csv'
df = pd.read_csv(infilename, index_col=0)

chart3 = Chart(df, barcols=df.columns, barstack=False,
               barlinewidth=0, xtickangle=90, xticklength=0,
               title='Categorical Data',
               yrange=[-15, 15],
               legend=False)
```

### Categorical Data with Margins

Specify the margins in units of a category.

```{python}
#| label: gallery_xaxis_categorical_options
#| fig-cap: "Categorical Data With Margins"
#| code-fold: show

infilename = 'data/turkey_page5/fig5_chart3_terms_of_trade.csv'
df = pd.read_csv(infilename, index_col=0)

chart3 = Chart(df, barcols=df.columns, barstack=False,
               barlinewidth=0, xtickangle=90, xticklength=0,
               title='Categorical Data',
               margins=2,
               yrange=[-15, 15],
               legend=False)
```

:::

### Formatting Axis Ticks

In most cases the library will handle axis ticks automatically.
This includes

- the (approximate) number of tickson each axis
- the formatting of the x-axis, which can be a datetime, number or category
- the tick lengths, tick label font size, tick label angle, padding between ticks and labels

Below are the options that can be passed in for ticks when creating a `Chart` object.

| Argument | Default | Description |
|---|---|---|
| xtickfontsize | None | X-axis tick label font size. Defaults to `'xtick.labelsize'` in `matplotlib.rcParams` unless specified. |
| ytickfontsize | None | Y-axis tick label font size. Defaults to `'ytick.labelsize'` in `matplotlib.rcParams` unless specified. |
| xticklength | None | X-axis tick length. Defaults to `'xtick.major.size'` in `matplotlib.rcParams` unless specified. |
| yticklength | None | Y-axis tick length. Defaults to `'ytick.major.size'` in `matplotlib.rcParams` unless specified. |
| xtickpad | None | X-axis padding between tick and labels. Defaults to `'xtick.major.pad'` in `matplotlib.rcParams` unless specified. |
| ytickpad | None | Y-axis padding between tick and labels. Defaults to `'ytick.major.pad'` in `matplotlib.rcParams` unless specified. |
| xtickangle | 0 | X-axis label angle. |
| ytickangle | 0 | Y-axis label angle. |
| nticksx | 'auto' | X-axis tick numbers. Use `'auto'` to set automatically, or specify integer. |
| nticksy | None | Uses `Matplotlib` defaults if `None` is specified, can also specify as integer. |
| last | False | If specified, replaces last default label of time series x-axis with latest data point. |
| xticks | None | Iterable specifying each tick position along x-axis. |
| xlabels | None | Iterable specifying each tick label along x-axis. Length must match `xticks`. |
| yticks | None | Iterable specifying each tick position along y-axis. |
| ylabels | None | Iterable specifying each tick label along y-axis. Length must match `yticks`. |
| ryticks | None | Iterable specifying each tick position along right y-axis. |
| rylabels | None | Iterable specifying each tick label along right y-axis. Length must match `ryticks`. |

: {tbl-colwidths="[10,10, 80]"}

Internally the function `chart.ticks()` is called with the above parameters.
The `chart.ticks()` function will take in the above options but the parameters are the following.

| Argument | Default | Description |
|---|---|---|
| axis | 'x' | Axis to modify, specify `'x'` or `'y'`. |
| yaxis | 'left' | In case modifying right y-axis, specify `'right'`. |
| size | None | Tick label font size. Defaults to 'xtick.labelsize' in `matplotlib.rcParams` if not specified. Specified as `xtickfontsize` or `ytickfontsize` within `Chart()` |
| length | None | Tick length. Defaults to 'xtick.major.size' in `matplotlib.rcParams` if not specified. Specified as `xticklength` or `yticklength` within `Chart()` |
| angle | None | Tick label angle. Defaults to 0 if not specified. Specified as `xtickangle` or `ytickangle` within `Chart()` |
| nticks | None | Number of ticks. For x-axis, defaults to `'auto'` while for y-axis uses `Matplotlib` defaults. Specified as `nxticks` or `nyticks` within `Chart()` |
| ticks | None | Iterable speciying location of ticks. |
| labels | None | Iterable speciying labels of ticks. |

: {tbl-colwidths="[10,10, 80]"}

For charts where the x-axis is a datetime, which is the case for time series charts, the positioning of the ticks
are determined so that there are roughly 7 or so tick labels.
Note that the format of the tick labels was explained in @sec-basics-format_axes, and this is by default determined
by the frequency of the data.

When the option `last=True` is specified in either `Chart()` or `Chart.ticks()`, the final tick position and label
are set to be the last data point. This can be a convenient way to signal when the data ends.
The option to specify integers for `nticks` is limited to the y-axis. For custom x-axis tick positions and labels
it is recommended to use the options `ticks` and `labels` to specify them directly.
If the options `ticks` or `labels` are used, any options for `last` and `nticks` will be ignored.

Below are examples of specifying the tick options when creating the `Chart` or modifying the ticks later by calling `Chart.ticks()`.

::: {.panel-tabset}

```{python}
#| label: basics_ticks_data
infilename = 'data/turkey_page5/fig5_chart2_current_account_mms.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0]).dropna(how='all', axis=0)
```

### No options

No options are provided for the ticks.

```{python}
#| label: gallery_ticks_nooptions
#| fig-cap: "Defaults"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
              title='No options',
              xrange='2022-01:', yrange=[-95, 60],
              legend_bottom=0.22, legend_left=0.55)
```

### Specify options

Options are provided for the ticks.

```{python}
#| label: gallery_ticks_options
#| fig-cap: "Specify tick options"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
              title='With options',
              xrange='2022-01:', yrange=[-95, 60],
              legend_bottom=0.22, legend_left=0.55,
              xtickfontsize=15, ytickfontsize=15,
              xticklength=10, yticklength=10,
              xtickpad=10, ytickpad=10,
              xtickangle=90, ytickangle=45)
```

### Call `ticks()`

No options are passed in when creating the `Chart` but are specified by calls to the `Chart.ticks()` function.

```{python}
#| label: gallery_ticks_func
#| fig-cap: "Call `Chart.ticks()`"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
              title='Call Chart.ticks()',
              legend_bottom=0.22, legend_left=0.55,
              xrange='2022-01:', yrange=[-95, 60])
# Call chart.ticks()
chart.ticks(axis='x', size=15, length=10, angle=90, pad=10)
chart.ticks(axis='y', size=15, length=10, angle=45, pad=10)
```

### Set number of ticks as integer

In the below `nticksy=20` is specified.
Note that specifying `nticksx` to be an integer for a datetime axis is not permitted.
This is because just setting MaxNLocator(nbins) will not align the dates to be
at the specific locations that the option "auto" will use.

```{python}
#| label: gallery_ticks_nticks
#| fig-cap: "Specify number of ticks as integer"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
              title='Integer nticks',
              legend_bottom=0.22, legend_left=0.55,
              xrange='2022-01:', yrange=[-95, 60],
              nticksy=20)
```

### Specify last date

In the below `last=True` is specified.
This will show the date of the last data point.

```{python}
#| label: gallery_ticks_last
#| fig-cap: "Specify last date"
#| code-fold: show
chart = Chart(df, linecols=df.columns,
              title='Integer nticks',
              legend_bottom=0.22, legend_left=0.55,
              xrange='2022-01:', yrange=[-95, 60],
              last=True)
```

### Specify ticks and label positions for x-axis

In the below `xticks` and `xlabels` are specified.

```{python}
#| label: gallery_ticks_customx
#| fig-cap: "Specify x-axis tick locations and labels"
#| code-fold: show
ticks = ['2022-01-01', '2023-05-01', '2024-07-01', '2025-05-01']
labels = ['Jan 22', 'May 2023', '7-24', 'May of 2025']

chart = Chart(df, linecols=df.columns,
              title='Specify x-axis tick locations and labels',
              legend_bottom=0.22, legend_left=0.55,
              xrange='2022-01:', yrange=[-95, 60],
	      xticks=ticks, xlabels=labels)
```

### Specify ticks and label positions for y-axis

In the below `yticks` and `ylabels` are specified.
Note that 

```{python}
#| label: gallery_ticks_customy
#| fig-cap: "Specify y-axis tick locations and labels"
#| code-fold: show
ticks = [-75, -10, 33, 55]
labels = ['lower', 'low', 'mid' ,'high']

chart = Chart(df, linecols=df.columns,
              title='Specify y-axis tick locations and labels',
              legend_bottom=0.22, legend_left=0.55,
              xrange='2022-01:', yrange=[-95, 60],
	      yticks=ticks, ylabels=labels)
```

:::


## Note on Available Colors {#sec-basics-misc-colors}

Given that colors are an important aesthetic in all charts, this section explains the colors available.
Colors can be specified as one of the following:

- A valid `Matplotlib` color (see [List of named colors](https://matplotlib.org/stable/gallery/color/named_colors.html){target="_blank"}.
  This includes basic colors like `'red'`, `'black'` as well as named HTML colors such as `'dodgerblue'`, `'lime'` and even [XKCD colors](https://xkcd.com/color/rgb/){target="_blank"}
- A color hex code specified as a `str` with format "#RRGGBB" where each of RR, GG, BB are hexadecimal values from "00" to "FF".
- An RGBA string of the form (r, g, b, t) where r, g, b are values between 0 - 1 and t is the transparency, also 0 - 1.
- Several colors are defined as `IMFBLUE`, `IMFRED`, `IMFGREEN`, `IMFGREY`, `IMFBLACK` and are imported from `imfcharts`.

See the gallery below for examples.

```{python}
#| label: basics_color_data
infilename = 'data/turkey_page5/fig5_chart2_current_account_mms.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0]).dropna(how='all', axis=0)
```

::: {.panel-tabset}

### Named Colors

Using named basic colors, which are simplest and most intuitive to use.

```{python}
#| label: gallery_colors_basic
#| fig-cap: "Using Basic Colors"
#| code-fold: show

chart = Chart(df, linecols=df.columns,
               colors=['red', 'green', 'blue', 'magenta'],
               title='Basic Named Colors',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### CSS Colors

Using named CSS colors, which provide more flexibility but are somewhat difficult to remember.

```{python}
#| label: gallery_colors_css
#| fig-cap: "Using CSS Colors"
#| code-fold: show

chart = Chart(df, linecols=df.columns,
               colors=['firebrick', 'lawngreen', 'darkturquoise', 'darkviolet'],
               title='CSS Colors',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### XKCD Colors

Using named XKCD colors, which are are fun to use.
Note that the names must be preceded by "xkcd:" followed by the name as-is from [here](https://xkcd.com/color/rgb/){target="_blank"}.

```{python}
#| label: gallery_colors_xkcd
#| fig-cap: "Using XKCD Colors"
#| code-fold: show

chart = Chart(df, linecols=df.columns,
               colors=['xkcd:pea green', 'xkcd:dark brown', 'xkcd:kelly green', 'xkcd:bright purple'],
               title='XKCD Colors',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### HEX Colors

Using HEX colors of the form "#RRGGBB", where each of RR, GG, BB are represented from 00 to FF.
This is not intuitive, but provides a way to implement the color if known from other sources in this format.

```{python}
#| label: gallery_colors_hex
#| fig-cap: "Using HEX Colors"
#| code-fold: show

chart = Chart(df, linecols=df.columns,
               colors=['#EE2222', '#22EF33', '#3232DD', '#DD54DE'],
               title='HEX Colors',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### RGBA Colors

Using RGBA colors which are a tuple of the form (r, g, b, t) where each of
r, g, b, t are the red, green, blue and trasnsparency, float values between 0 and 1.
This is not intuitive, but provides a way to implement the color if known from other sources in this format.

```{python}
#| label: gallery_colors_rgba
#| fig-cap: "Using RGBA Colors"
#| code-fold: show

chart = Chart(df, linecols=df.columns,
               colors=[(0.9, 0.05, 0.1, 0.7), (0.2, 0.85, 0.1, 0.8), (0.25, 0.05, 0.9, 0.6), (0.85, 0.25, 0.85, 0.6)],
               title='RGBA Colors',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### IMF Colors

Some colors for the Fund are defined within the library.
These colors are the following: `AXISGREY` : '#B3B3B3', `AXISGRAY` : '#B3B3B3', `IMFBLUE` : '#4B82AD',
`IMFGREEN` : '#96BA79', `IMFRED` : '#C00000', `IMFGREY` : '#A6A8AC', `IMFGRAY` : '#A6A8AC', `IMFBLACK` : '#000000',

: {tbl-colwidths="[40,60]"}

```{python}
#| label: gallery_colors_imf
#| fig-cap: "Using IMF Colors"
#| code-fold: show

chart = Chart(df, linecols=df.columns,
               colors=[IMFRED, IMFGREEN, IMFBLUE, IMFGREY],
               title='IMF Colors',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

:::

## Non-Western Languages

The library can be used with languages other than those using standard Western fonts.
The basic way to do this is to specify the internal `Matplotlib` parameter in the following way

```{python}
#| label: change_lang
matplotlib.rcParams["font.family"] = "Microsoft YaHei"
```

so that a font set that has the necessary fonts is used.
Given that it is not clear which fonts are usable for a given language, an option `lang` is given when
creating the `Chart` object so that this can be specified with the [2-letter language code](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes){target="_blank"}. In particular, the options `lang='jp'` and `lang='zh'` for Japanese and Chinese are implemented.
Otherwise for Western European language families and Arabic, the default will work.
In cases where a specific language needs to be implemented, search for `Matplotlib` fonts that implement that language and
use the option `fontname` when creating the `Chart`.

Below are several examples of specifying the `lang` or `fontname` parameter.

```{python}
#| label: data_lang

# Read in data
infilename = 'data/turkey_page5/fig5_chart2_current_account_mms.csv'
df = pd.read_csv(infilename, index_col=0, parse_dates=[0]).dropna(how='all', axis=0)
```

::: {.panel-tabset}

### Default (Segoe-UI)


```{python}
#| label: gallery_lang_segoeui
#| fig-cap: "Using Default Segoe UI"
#| code-fold: show
title='Current Account'
subtitle='(Billions USD, 12mms)'
xtitle = 'date'
ytitle = 'U.S. $B'

chart2 = Chart(df, linecols=df.columns,
               title=title,
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### Specify fontname


```{python}
#| label: gallery_lang_arial
#| fig-cap: "Using `fontname='Arial'`"
#| code-fold: show
chart2 = Chart(df, linecols=df.columns,
               fontname='Arial',
               title=title + ' (Arial)',
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### French

```{python}
#| label: gallery_lang_fr
#| fig-cap: "French"
#| code-fold: show
title='Face à des forces divergentes, l’économie mondiale reste stable'
subtitle='La croissance s’avère résiliente'
xtitle = 'date'
ytitle = 'L’économie mondiale'

chart2 = Chart(df, linecols=df.columns,
               title=title,
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### Arabic

```{python}
#| label: gallery_lang_ar
#| fig-cap: "Arabic"
#| code-fold: show
title='الاقتصاد العالمي: استقرار وسط قوى متباينة'
subtitle='يُتَوَقَّع بلوغ النمو العالمي 3,3% في'
xtitle = 'آخر توقعات النمو 2026'
ytitle = 'الهيكل التنظيمي للصندوق'

chart2 = Chart(df, linecols=df.columns,
               title=title,
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### Chinese

```{python}
#| label: gallery_lang_zh
#| fig-cap: "Chinese"
#| code-fold: show

title = '全球经济：在分化力量中保持平稳'
subtitle = '经济增长呈现出韧性'
xtitle = '并实施结构性改革'
ytitle = '增长率预测'

chart2 = Chart(df, linecols=df.columns,
               title=title,
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55,
	       lang='zh')
```

### Japanese

```{python}
#| label: gallery_lang_jp
#| fig-cap: "Japanese"
#| code-fold: show

title = '世界経済'
subtitle = '成長底堅く'
xtitle = '貿易摩擦の安定化と良好な金融環境'
ytitle = '輸出の底堅さ'

chart2 = Chart(df, linecols=df.columns,
               title=title,
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55,
	       lang='jp')
```

### Georgian (specify `fontname`)

```{python}
#| label: gallery_lang_ka
#| fig-cap: "Georgian"
#| code-fold: show

title = "მსოფლიო ეკონომიკური ზრდა"
subtitle = 'წლიური ზრდის ტემპები'
xtitle = 'თარიღი'
ytitle = 'მილიარდი აშშ დოლარი'
df.columns = ['მიმდინარე ანგარიში', 'საწვავის გამოკლებით', 'საწვავისა და ოქროს გამოკლებით', 'ოქროს გამოკლებით']

chart2 = Chart(df, linecols=df.columns,
               title=title,
               subtitle=subtitle,
               xtitle=xtitle, ytitle=ytitle,
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55,
	       fontname='Sylfaen')
```

:::

<!------------------------------------------------------------------------------------------------------------------------------------>
# Switching Styles {#sec-styles}

The `imfcharts` package is available with several pre-defined styles which will automatically set the style to be that for IMF Article IV reports, etc.
One of the main purposes of this library is to allow switching between styles to be easy.
By doing this charts can be customized not just for existing styles but can be reused for any future changes in style.

When the `imfcharts` library is imported, it will automatically copy the available style files to where `Matplotlib` can find them.
To copy styles manually, do

```python
from imfcharts import *
install_styles(force=True)
```

which will copy the style files to `matplotlib.get_configdir() + '/stylelib'` which is typically `C:\Users\[user]\.matlotlib\stylelib`
on a Fund laptop.

The command

```{python}
#| label: show_styles
#| code-fold: show
#| eval: true
#| output: true
# This is just returning plt.style.available
show_styles()
```

will show all available styles, including ones that are included from `Matplotlib` and other libraries.

To switch styles, call the command

```{python}
#| eval: false
#| code-fold: show
# This is just a wrapper around plt.style.use() with some guardrails
# and reloading the style file.
set_style('imf-articleiv')
```

To temporarily switch styles, do the following.

```{python}
#| label: get_data_ca


# Get data
cacol = 'Current account'
dict_series = {'N186BC@EMERGEMA' : cacol,
               'N186IX3@EMERGEMA' : 'export_fuel',
	       'N186IM3@EMERGEMA' : 'import_fuel',
               'N186BGXN@EMERGEMA' : 'export_gold',
	       'N186BGMN@EMERGEMA' : 'import_gold'}
df = None
for series in dict_series:
    _df = imf_datatools.get_haver_data(series)
    _df.columns = [dict_series[series]]
    if df is None:
        df = _df
    else:
        df = df.merge(_df, left_index=True, right_index=True, how='outer')
df['Excluding fuel'] = df[cacol] - (df['export_fuel'] - df['import_fuel'])
df['Excluding fuel & gold'] = df[cacol] - (df['export_fuel'] - df['import_fuel']) - (df['export_gold'] - df['import_gold'])
df['Excluding gold'] = df[cacol] - (df['export_gold'] - df['import_gold'])
df.drop(['export_fuel', 'import_fuel', 'export_gold', 'import_gold'], axis=1, inplace=True)

# Take 12-month moving sum and divide by 1000
df = df.rolling(12).sum() / 1000
```

```{python}
#| label: style_comparison
#| fig-cap: "Switching styles."
#| code-fold: show
# Create Chart object with default IMF Article IV style
set_style('imf-articleiv')
chart = Chart(df, linecols=df.columns,
              title='Current Account', subtitle='(Billions USD, 12mms)',
              xrange='2022-01:', yrange=[-95, 60],
              legend_bottom=0.28, legend_left=0.60, height=4)
chart
```

```{python}
#| label: style_comparison2
#| fig-cap: "Switching styles."
#| code-fold: show
# Create Chart object with Fund Guide style
set_style('fund-guide')
chart2 = Chart(df, linecols=df.columns,
               title='Current Account', subtitle='(Billions USD, 12mms)',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.28, legend_left=0.60, height=4)
chart2

# Set back to default for subsequent charts
set_style('imf-articleiv')
```

It is also possible to switch styles temporarily for a single chart with the following:

```{python}
#| label: style_comparison3
#| fig-cap: "Switching styles."
#| code-fold: show

with style('ggplot'):
    chart2 = Chart(df, linecols=df.columns,
                   title='Current Account', subtitle='(Billions USD, 12mms)',
                   xrange='2022-01:', yrange=[-95, 60],
                   legend_bottom=0.28, legend_left=0.60, height=4)
    chart2
```

Here the `style()` function can take on any valid style name and set the style for any chart within the context window.
The `style()` function can take in any number of styles and also any parameters of a style file that should be customized.
For example, in the below, the basic style is set to the `"dark_background"` style that is included in `Matplotlib`,
but the default linestyle is set to "--".

```{python}
#| label: style_comparison4
#| fig-cap: "Switching styles."
#| code-fold: show

with style('dark_background', {'lines.linestyle' : '--'}):
    chart2 = Chart(df, linecols=df.columns,
                   title='Current Account', subtitle='(Billions USD, 12mms)',
                   xrange='2022-01:', yrange=[-95, 60],
                   legend_bottom=0.28, legend_left=0.60, height=4)
    chart2
```

In this way it is possible to customize certain features of an existing style.
While these features exist for completeness, the original goal of the `imfcharts` library is to set the default style
in a way that the user does not need to worry about the style and use as-is.

Below is a gallery of using different styles and how to specify them, as well as additional parameters.

```{python}
#| label: styles_data
# Read in data
infilename = 'data/turkey_page5/fig5_chart2_current_account_mms.csv'
if not os.path.isfile(infilename):
    print('File ' + infilename + ' does not exist')
    sys.exit()
df = pd.read_csv(infilename, index_col=0, parse_dates=[0]).dropna(how='all', axis=0)
```

::: {.panel-tabset}

### Default

Use default IMF Article IV style.

```{python}
#| label: gallery_styles_default
#| fig-cap: "Default IMF Article IV"
#| code-fold: show
chart2 = Chart(df, linecols=df.columns,
               title='Default IMF Article IV',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
```

### Specify style

If a style is specified, the style will be used for all charts until changed.

```{python}
#| label: gallery_styles_change
#| fig-cap: "Change Style for All Charts"
#| code-fold: show
# Use show_styles() to show available styles
set_style('classic')
chart2 = Chart(df, linecols=df.columns,
               title='Set style with set_style()',
               xrange='2022-01:', yrange=[-95, 60],
               legend_bottom=0.22, legend_left=0.55)
# Reset style to default
set_style('imf-articleiv')
```

### Use Context Manager

A context manager allows specifying styles for a given figure.
It can be one or multiple styles, and 

If a style is specified, the style will be used for all charts until changed.

```{python}
#| label: gallery_styles_context_manager
#| fig-cap: "Context Manager"
#| code-fold: show
# Use show_styles() to show available styles
with style('dark_background'):
    chart2 = Chart(df, linecols=df.columns,
                   title='single style in context manager',
                   xrange='2022-01:', yrange=[-95, 60],
                   legend_bottom=0.22, legend_left=0.55)
```

### Use Context Manager with Multiple Styles

Multiple styles can be specified and they are applied consecutively.
Note that the styles are applied in the order specified, so that
in the below the grids from the `ggplot` style are shown but the background
color is overridden by the `dark_background` style.

```{python}
#| label: gallery_styles_context_manager_multiple
#| fig-cap: "Multiple Context Managers"
#| code-fold: show
# Use show_styles() to show available styles
with style(['ggplot', 'dark_background']):
    chart2 = Chart(df, linecols=df.columns,
                   title='Multiple styles in context manager',
                   xrange='2022-01:', yrange=[-95, 60],
                   legend_bottom=0.22, legend_left=0.55)
```

### Use Context Manager with Multiple Styles

Besides a specifying style(s), specific `matplotlib.rcParams` can be specified.
In the below, the 'tableau-colorblind10' style is used but the default line style is set to dashed.
This can of course be overridden by specifying `attrs` when charting.

```{python}
#| label: gallery_styles_context_manager_rc
#| fig-cap: "Context Manager with rcParams"
#| code-fold: show
# Use show_styles() to show available styles
with style('tableau-colorblind10', rc={'lines.linestyle' : '--'}):
    chart2 = Chart(df, linecols=df.columns,
                   title='Multiple styles in context manager',
                   xrange='2022-01:', yrange=[-95, 60],
                   legend_bottom=0.22, legend_left=0.55)
```

:::

## Summary of Commands Related to Styles

| Argument | Description |
|---|---|
| show_styles() | Show all available styles |
| install_styles(force=False) | Copy all .mplstyle files from `imfcharts` to where `Matplotlib` can find them. Use `force=True` to overwrite existing files. |
| update_style(stylename) | If a style file is edited within the `imfcharts` library, copy and update within `Matplotlib` |
| set_style(stylename) | Set the current style until it is changed again |
| style(style=None, rc=None) | Context manager to temporarily change style or rcParams. `style` can be a single existing style name or an iterable of styles. `rc` is a `dict` containing valid `matplotlib.rcParams` as keys. |

: {tbl-colwidths="[22, 78]"}

<!------------------------------------------------------------------------------------------------------------------------------------>
# Usage in R {#sec-R}

The `imfcharts` library can be used directly in R by importing it through the [`reticulate`](https://rstudio.github.io/reticulate/){target="_blank")
package which is officially supported by RStudio. Users familiar with the [`datatools`](http://datatools){target="_blank"} will be
familiar with this procedure. Below is sample code showing how the library and its components can be imported and used in R.

```r
# Read in necessary libraries
library(reticulate)
library(readr)
library(dplyr)       
library(tibble)     

# Import imfcharts and make functions like Charts() available
imfcharts <- import("imfcharts")

# Attach all chart objects to the global environment
# This is the equivalent of doing
# from imfcharts import *
# in Python
for (name in names(imfcharts)) {
  assign(name, imfcharts[[name]], envir = .GlobalEnv)
}
```

The usage in R is very similar to that in Python, the only syntax changes are that instead of using a period to
access class members, a dollar sign is used. So for example the code
```{python}
#| label: usage_r_py
#| eval: false
#| code-fold: show
chart = Chart(df, linecols=cols)
chart.hline(y=100)
```

becomes in R:
```r
chart <- Chart(df, linecols=cols)
chart$hline(y=100)
```

An important thing to note is how to pass a DataFrame in R to the Python code.
In general, Python's `pandas` libraries assumes an index which is separate from the columns of the data,
and time series DataFrames are typically manipulated by utilizing this index for various calculations.
In the case of R DataFrames, there is no one standard, and in some cases the index will be a column with
equal footing as other colunmns containing data. The `imfcharts` library has a parameter
`indexcol` when creating a `Chart` object or when adding visuals through functions like `Chart.lines()`,
`Chart.bars()`, `Chart.area()`, `Chart.fill()`. When `indexcol` is specified, the specified column will
be set internally as the index, and if it is specified as a column to draw for example in the following,
it will be ignored.

```{python}
#| label: usage_r_indexcol
#| eval: false
#| code-fold: show
# Even though the indexcol is specified as one of the columns to draw lines for
# with `linecols=df.columns`, since it will be used as the `indexcol`,
# no attempt will be made to draw it.
chart = Chart(df, indexcol='dates', linecols=df.columns)
```
 Below are examples showing how DataFrames in R can
be constructed and how they can be passed into the `imfplotly` library.
Note that the Python `dict` for `attrs` is created as a `dict` from the `reticulate` library,
and that the y-axis ranges, which are `list`s in Python are given with the `c()` function.

```r

# ---------------------------------------------------------------------
# Create attrs  in R
# ---------------------------------------------------------------------
attrs <- dict(
  `Risk weighted Assets (RHS)` = dict(color = IMFBLACK),
  Capital                      = dict(color = IMFBLUE),
  `Core capital`               = dict(color = IMFRED)
)

# ---------------------------------------------------------------------
# 1. Read in a csv file and use column_to_rownames to
# set the column as index (row names)
# ---------------------------------------------------------------------
df_r <- read_csv("data/turkey_page6/fig6_chart1_current_account.csv") %>% 
  mutate(dates = lubridate::ymd(dates)) %>% 
  arrange(dates) %>% 
column_to_rownames("dates")

# Create chart
chart1 <- Chart(df_r,
  linecols=c("Capital", "Core capital"), rlinecols="Risk weighted Assets (RHS)",
  attrs=attrs,
  title="Bank Capital", subtitle="(Percent of risk-weighted assets; RWA y/y percent change)",
  legend_left = 0.4,
  xrange="2022-01:", yrange=c(10, 25), ryrange=c(120, 200)
)
```

```r
# ---------------------------------------------------------------------
# 2. Read in the same csv file but do not set index
# ---------------------------------------------------------------------
df_r2 <- read_csv("data/turkey_page6/fig6_chart1_current_account.csv") %>% 
  mutate(dates = lubridate::ymd(dates)) %>% 
  arrange(dates)

# Create chart
chart2 <- Chart(df_r2, indexcol='dates',
  linecols= c("Capital", "Core capital"), rlinecols = "Risk weighted Assets (RHS)",
  attrs=attrs,
  title="Bank Capital", subtitle="(Percent of risk-weighted assets; RWA y/y percent change)",
  legend_left=0.4,
  xrange="2022-01:", yrange=c(10, 25), ryrange=c(120, 200)
)
```

```r
# ---------------------------------------------------------------------
# 3. Convert R DataFrame to pandas and set index to datetime
# ---------------------------------------------------------------------
py_df <- r_to_py(df_r)
# Below is to convert the index to datetime, not necessary but good practice
py_df$index <- pd$to_datetime(py_df$index)

chart3 <- Chart(py_df,
  linecols=c("Capital", "Core capital"), rlinecols="Risk weighted Assets (RHS)",
  attrs=attrs,
  title="Bank Capital", subtitle="(Percent of risk-weighted assets; RWA y/y percent change)",
  legend_left=0.4,
  xrange="2022-01:", yrange=c(10, 25), ryrange=c(120, 200)
)
```

See the file `examples/examples.R` under the installation of `imfcharts`
(for Fund computeres this will typically be `C:\ProgramData\Python3\site-packages\imfcharts`)
for an example R script that will use the `imfcharts` library.

<!------------------------------------------------------------------------------------------------------------------------------------>
# Usage in Stata {#sec-stata}

Stata has its own powerful visualization library, and this can also be used for official Fund publications.
For code to create custom Article IV charts, contact [the datatools team](mailto:datatools-support@imf.org).

Currently the `imfcharts` library is not callable from Stata, but in the future it may be possible.
The `imfcharts` library can be called from any AI system, but due to license constraints, it is not easy to use Stata within these systems.
This document will be updated iff a solution is found where Stata users can easily integrate this into their workflow.

<!------------------------------------------------------------------------------------------------------------------------------------>
# Usage in AI, Excel {#sec-ai-excel}

How to use in AI



